import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
async function main(){
 const db=new PGlite();let checks=0;const check=(a:unknown,b:unknown)=>{assert.deepEqual(a,b);checks++};
 const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
 const canonical=await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8');
 const table=(name:string)=>{const sql=canonical.match(new RegExp('create table public\\.'+name+' \\([\\s\\S]*?^\\);','mi'))?.[0];assert.ok(sql,name);return sql};
 const fn=(name:string)=>{const sql=canonical.match(new RegExp('create or replace function public\\.'+name+'\\([\\s\\S]*?\\$\\$;','i'))?.[0];assert.ok(sql,name);return sql};
 const project=randomUUID(),contact=randomUUID(),initial=randomUUID(),deleted=randomUUID(),invoice=randomUUID();
 const insert=async(id:string,amount='5000',status='draft',lines:unknown[]=[])=>db.query('INSERT INTO project_invoices(id,project_id,invoice_number,amount,status,date,line_items) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)',[id,project,'SYN-'+id.slice(0,8),amount,status,'2026-06-01',JSON.stringify(lines)]);
 const head=async(id:string)=>(await db.query<{revision:number;body:Record<string,any>;history_origin:string}>('SELECT * FROM invoice_accounting_heads WHERE invoice_id=$1',[id])).rows[0];
 const service=async(id:string,cursor:number|null=null)=>{await db.exec('SET ROLE service_role');try{return(await db.query<{r:any}>('SELECT invoice_accounting_snapshot($1,$2) r',[id,cursor])).rows[0].r}finally{await db.exec('RESET ROLE')}};
 try{
  await db.exec('CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE SEQUENCE public.webhook_event_seq;');
  for(const name of ['team_members','contacts','projects','project_contacts','project_invoices','webhook_endpoints','webhook_events','webhook_deliveries'])await db.exec(table(name));
  await db.exec(fn('emit_invoice_webhook'));await db.exec(fn('claim_webhook_deliveries'));await db.exec('CREATE TRIGGER emit_invoice_webhook AFTER INSERT OR UPDATE OR DELETE ON project_invoices FOR EACH ROW EXECUTE FUNCTION emit_invoice_webhook()');
  await db.exec("CREATE FUNCTION has_permission(text) RETURNS boolean LANGUAGE sql AS $$ SELECT current_setting('test.webhook_permission',true)='yes' $$");
  await db.query('INSERT INTO projects(id,name,tax_rate) VALUES($1,$2,10)',[project,'Synthetic client project']);await db.query('INSERT INTO contacts(id,name,company) VALUES($1,$2,$3)',[contact,'Synthetic client','Synthetic LLC']);await db.query('INSERT INTO project_contacts(project_id,contact_id,is_primary_client) VALUES($1,$2,true)',[project,contact]);
  await db.query("INSERT INTO webhook_endpoints(name,url,secret,events) VALUES('Legacy personal income','https://synthetic.invalid/legacy','synthetic-secret',ARRAY['invoice.paid','invoice.updated','invoice.deleted']),('Accounting lifecycle','https://synthetic.invalid/accounting','synthetic-secret',ARRAY['invoice.lifecycle'])");
  await insert(initial);await insert(deleted,'100','paid');await db.query('DELETE FROM project_invoices WHERE id=$1',[deleted]);
  await db.exec(await readFile(new URL('../supabase/schema/accounting-invoice-source.sql',import.meta.url),'utf8'));
  check((await head(initial)).history_origin,'bootstrap');check((await head(deleted)).body.deleted,true);check((await head(deleted)).body.invoice.total_cents,null);
  check((await db.query<{n:number}>("SELECT count(*)::int n FROM webhook_events WHERE event_type='invoice.lifecycle'")).rows[0].n,0);
  await insert(invoice,'120','draft',[{id:'service',item_type:'fixed',amount:100,description:'Work',position:0},{id:'cost',item_type:'reimbursement',amount:20,description:'Reimbursable cost',position:1}]);
  check((await head(invoice)).body.invoice.subtotal_cents,'12000');check((await head(invoice)).body.invoice.total_cents,'13000');check((await head(invoice)).body.tax.amount_cents,'1000');check((await head(invoice)).history_origin,'created');
  await db.query("UPDATE project_invoices SET status='sent' WHERE id=$1",[invoice]);check(Number((await head(invoice)).revision),2);
  await db.query("UPDATE project_invoices SET status='paid',paid_date='2026-06-20' WHERE id=$1",[invoice]);check(Number((await head(invoice)).revision),3);check((await head(invoice)).body.invoice.payment_claimed,true);
  const priorEvents=(await db.query<{n:number}>('SELECT count(*)::int n FROM webhook_events')).rows[0].n;await db.query('UPDATE project_invoices SET updated_at=now() WHERE id=$1',[invoice]);check(Number((await head(invoice)).revision),3);check((await db.query<{n:number}>('SELECT count(*)::int n FROM webhook_events')).rows[0].n,priorEvents);
  check((await db.query<{n:number}>("SELECT count(*)::int n FROM webhook_events WHERE resource_id=$1 AND event_type='invoice.paid'",[invoice])).rows[0].n,1);
  await db.query('UPDATE contacts SET company=$2 WHERE id=$1',[contact,'Renamed synthetic LLC']);check((await head(invoice)).body.customer.company,'Renamed synthetic LLC');check(Number((await head(invoice)).revision),4);
  await db.query('UPDATE projects SET tax_rate=5,name=$2 WHERE id=$1',[project,'Updated synthetic project']);check((await head(invoice)).body.invoice.total_cents,'12500');check((await head(invoice)).body.project.name,'Updated synthetic project');
  await db.query('UPDATE project_invoices SET line_items=$2::jsonb WHERE id=$1',[initial,JSON.stringify([{id:'bad',amount:'1.001',item_type:'fixed'}])]);check((await head(initial)).body.issues.includes('invalid_line_amount'),true);check((await head(initial)).body.invoice.total_cents,null);
  await db.query("UPDATE project_invoices SET line_items='{}',date='2026-02-30' WHERE id=$1",[initial]);check((await head(initial)).body.issues.includes('invalid_issue_date'),true);check((await head(initial)).body.issues.includes('unsupported_line_count'),true);
  await db.query("UPDATE project_invoices SET line_items='[]',date='2026-06-01' WHERE id=$1",[initial]);
  for(let i=0;i<101;i++)await insert(`a0000000-0000-4000-8000-${String(i).padStart(12,'0')}`,'1');
  const snapshot=randomUUID(),meta=await service(snapshot),first=await service(snapshot,0);check(meta.item_count,104);check(first.records.length,100);check(first.next_cursor,100);
  const lastId='a0000000-0000-4000-8000-000000000100';await db.query('UPDATE project_invoices SET amount=2 WHERE id=$1',[lastId]);await db.query('DELETE FROM project_invoices WHERE id=$1',[invoice]);
  const second=await service(snapshot,first.next_cursor),records=[...first.records,...second.records];check(second.next_cursor,null);check(records.find(r=>r.invoice_id===lastId).revision,'1');check(JSON.parse(records.find(r=>r.invoice_id===invoice).body).deleted,false);
  for(const record of records)assert.equal(hash(record.body),record.hash);checks++;
  check(hash(records.sort((a,b)=>a.invoice_id.localeCompare(b.invoice_id)).map(r=>`${r.invoice_id}:${r.revision}:${r.hash}`).join('\n')),meta.manifest_hash);
  const fresh=await service(randomUUID());check(fresh.item_count,104);check((await head(invoice)).body.deleted,true);check((await head(invoice)).body.invoice.total_cents,'12500');
  await db.exec('ALTER TABLE project_invoices DISABLE TRIGGER invoice_accounting_change');await db.query('UPDATE project_invoices SET amount=3 WHERE id=$1',[lastId]);await db.exec('ALTER TABLE project_invoices ENABLE TRIGGER invoice_accounting_change');check((await head(lastId)).body.invoice.subtotal_cents,'200');await service(randomUUID());check((await head(lastId)).body.invoice.subtotal_cents,'300');
  const oldVersion=(await head(lastId)).revision;await db.exec('BEGIN');await db.query('UPDATE project_invoices SET amount=9 WHERE id=$1',[lastId]);await db.exec('ROLLBACK');check((await head(lastId)).revision,oldVersion);
  await db.exec('SET ROLE authenticated');await assert.rejects(db.query('SELECT * FROM invoice_accounting_heads'),/permission denied/);checks++;await assert.rejects(db.query('SELECT invoice_accounting_snapshot($1,NULL)',[randomUUID()]),/permission denied/);checks++;await db.exec('RESET ROLE');
  await assert.rejects(db.query('DELETE FROM invoice_accounting_versions'),/INVOICE_SOURCE_IMMUTABLE/);checks++;
  await db.query("UPDATE invoice_accounting_snapshots SET expires_at=now()-interval '1 second' WHERE id=$1",[snapshot]);await assert.rejects(service(snapshot,0),/INVOICE_SNAPSHOT_EXPIRED/);checks++;
  // Exercise worker fencing against the real SQL state machine, without HTTP.
  await db.exec("UPDATE webhook_deliveries SET status='succeeded'");
  const one=randomUUID(),two=randomUUID();await insert(one,'12');await insert(two,'8');
  await db.query("UPDATE project_invoices SET amount=13 WHERE id=$1",[one]);
  const claim=async()=>(await db.query<any>('SELECT * FROM claim_webhook_deliveries(20)')).rows;
  const finish=async(id:string,token:string|null,status:number|null)=>(await db.query<{r:any}>('SELECT complete_webhook_delivery($1,$2,$3,$4,$5) r',[id,token,status,status===200?null:'Synthetic failure','Synthetic response'])).rows[0].r;
  const claimed=await claim();check(claimed.length,2);check(typeof claimed[0].event_sequence,'string');check((await claim()).length,0);
  const firstClaim=claimed.find(c=>c.payload.record.invoice_id===one);assert.ok(firstClaim);
  check((await finish(firstClaim.delivery_id,randomUUID(),200)).accepted,false);check((await finish(firstClaim.delivery_id,null,200)).accepted,false);
  check((await finish(firstClaim.delivery_id,firstClaim.attempt_token,503)).retry_scheduled,true);
  check((await finish(firstClaim.delivery_id,firstClaim.attempt_token,200)).accepted,false);
  check((await db.query<{ok:boolean}>('SELECT next_attempt_at>now() ok FROM webhook_deliveries WHERE id=$1',[firstClaim.delivery_id])).rows[0].ok,true);
  const later=await claim();check(later.length,1);await finish(later[0].delivery_id,later[0].attempt_token,200);
  await db.query("UPDATE webhook_deliveries SET next_attempt_at=now()-interval '1 second' WHERE id=$1",[firstClaim.delivery_id]);
  const retried=(await claim())[0];check(retried.delivery_id,firstClaim.delivery_id);check(retried.attempts,2);assert.notEqual(retried.attempt_token,firstClaim.attempt_token);checks++;
  await db.query("UPDATE webhook_deliveries SET lease_expires_at=now()-interval '1 second' WHERE id=$1",[retried.delivery_id]);
  check((await finish(retried.delivery_id,retried.attempt_token,200)).accepted,false);
  const recovered=(await claim())[0];check(recovered.delivery_id,retried.delivery_id);check(recovered.attempts,3);
  await db.query('UPDATE webhook_deliveries SET attempts=8 WHERE id=$1',[recovered.delivery_id]);check((await finish(recovered.delivery_id,recovered.attempt_token,503)).retry_scheduled,false);
  check((await db.query<{status:string}>('SELECT status FROM webhook_deliveries WHERE id=$1',[recovered.delivery_id])).rows[0].status,'failed');
  await db.exec('SET ROLE authenticated');await assert.rejects(db.query('SELECT requeue_webhook_delivery($1)',[recovered.delivery_id]),/WEBHOOK_FORBIDDEN/);checks++;
  await db.exec("SET test.webhook_permission='yes'");await db.query('SELECT requeue_webhook_delivery($1)',[recovered.delivery_id]);await db.exec('RESET ROLE');
  const manual=(await claim())[0];check(manual.attempts,1);
  await db.exec('SET ROLE authenticated');await assert.rejects(db.query('SELECT requeue_webhook_delivery($1)',[manual.delivery_id]),/WEBHOOK_BUSY/);checks++;await db.exec('RESET ROLE');
  await finish(manual.delivery_id,manual.attempt_token,200);
  await db.query("UPDATE project_invoices SET status='paid',paid_date='2026-06-20' WHERE id=$1",[one]);
  const legacy=(await claim()).find(c=>c.event_type==='invoice.paid');assert.ok(legacy);check((await finish(legacy.delivery_id,legacy.attempt_token,500)).retry_scheduled,false);
  check((await db.query<{status:string}>('SELECT status FROM webhook_deliveries WHERE id=$1',[legacy.delivery_id])).rows[0].status,'failed');
  await assert.rejects(db.query('SELECT * FROM claim_webhook_deliveries(NULL)'),/WEBHOOK_LIMIT/);checks++;
  console.log(`Accounting invoice source revisions, snapshots, delivery fencing and isolation: ${checks} assertions passed.`);
 }finally{await db.close()}
}
main().catch(e=>{console.error(e);process.exitCode=1});
