export interface EndpointDoc {
  method: string;
  path: string;
  description: string;
  group: string;
  params?: { name: string; type: string; required: boolean; description: string }[];
  queryParams?: { name: string; type: string; description: string }[];
  body?: { name: string; type: string; required: boolean; description: string }[];
}

export const endpoints: EndpointDoc[] = [
  // ─── Contacts ─────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/contacts', description: 'List all contacts with optional search and sorting. Returns paginated results.', group: 'Contacts',
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
      { name: 'search', type: 'string', description: 'Search by name, email, or company' },
      { name: 'sort', type: 'string', description: 'Sort field (default created_at)' },
      { name: 'order', type: 'asc|desc', description: 'Sort order (default desc)' },
    ],
  },
  { method: 'POST', path: '/api/v1/contacts', description: 'Create a new contact. Contacts represent people or organizations you interact with — clients, vendors, partners, etc.', group: 'Contacts',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Contact name' },
      { name: 'email', type: 'string', required: false, description: 'Email address (defaults to empty string if omitted)' },
      { name: 'phone', type: 'string', required: false, description: 'Phone number (defaults to empty string if omitted)' },
      { name: 'company', type: 'string', required: false, description: 'Company name (defaults to empty string if omitted)' },
      { name: 'notes', type: 'string', required: false, description: 'Free-text notes (defaults to empty string if omitted)' },
      { name: 'color', type: 'string', required: false, description: 'Hex color e.g. #5B8A8A (defaults to brand teal). Must match #RRGGBB format.' },
      { name: 'avatar_url', type: 'string', required: false, description: 'Avatar image URL' },
    ],
  },
  { method: 'GET', path: '/api/v1/contacts/:id', description: 'Get a single contact by ID', group: 'Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Contact ID' }],
  },
  { method: 'PATCH', path: '/api/v1/contacts/:id', description: 'Update a contact. Only include fields you want to change.', group: 'Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Contact ID' }],
    body: [
      { name: 'name', type: 'string', required: false, description: 'Contact name' },
      { name: 'email', type: 'string', required: false, description: 'Email address' },
      { name: 'phone', type: 'string', required: false, description: 'Phone number' },
      { name: 'company', type: 'string', required: false, description: 'Company name' },
      { name: 'notes', type: 'string', required: false, description: 'Free-text notes' },
      { name: 'color', type: 'string', required: false, description: 'Hex color (#RRGGBB)' },
      { name: 'avatar_url', type: 'string', required: false, description: 'Avatar image URL' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/contacts/:id', description: 'Permanently delete a contact', group: 'Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Contact ID' }],
  },

  // ─── Team Members ─────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/team-members', description: 'List all team members (human users and agent accounts). Returns paginated results.', group: 'Team Members',
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
      { name: 'search', type: 'string', description: 'Search by name or email' },
    ],
  },
  { method: 'POST', path: '/api/v1/team-members', description: 'Create a team member. Use role "agent" for AI agent accounts that can post suggestions and log activity.', group: 'Team Members',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Display name' },
      { name: 'email', type: 'string', required: true, description: 'Email address (must be valid format)' },
      { name: 'avatar', type: 'string', required: false, description: 'Avatar image URL (defaults to empty string)' },
      { name: 'role', type: 'admin|member|guest|agent', required: false, description: 'Role (default member). Use "agent" for AI agent accounts.' },
      { name: 'timezone', type: 'string', required: false, description: 'IANA timezone e.g. America/New_York (default UTC). Used for time entry timezone defaults.' },
      { name: 'auth_user_id', type: 'uuid|null', required: false, description: 'Supabase Auth user ID to link this member to a login account' },
      { name: 'email_notifications_enabled', type: 'boolean', required: false, description: 'Enable email notifications for this member (default: false)' },
      { name: 'email_notification_prefs', type: 'object', required: false, description: 'Email notification preferences. JSON object mapping category keys to booleans (default: all disabled).' },
    ],
  },
  { method: 'GET', path: '/api/v1/team-members/:id', description: 'Get a single team member by ID', group: 'Team Members',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Team member ID' }],
  },
  { method: 'PATCH', path: '/api/v1/team-members/:id', description: 'Update a team member. Only include fields you want to change.', group: 'Team Members',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Team member ID' }],
    body: [
      { name: 'name', type: 'string', required: false, description: 'Display name' },
      { name: 'email', type: 'string', required: false, description: 'Email address' },
      { name: 'avatar', type: 'string', required: false, description: 'Avatar URL' },
      { name: 'role', type: 'admin|member|guest|agent', required: false, description: 'Role' },
      { name: 'timezone', type: 'string', required: false, description: 'IANA timezone (e.g. America/New_York). Used for displaying times and as default timezone for API time entries.' },
      { name: 'notification_prefs', type: 'object', required: false, description: 'In-app notification preferences. JSON object mapping category keys to booleans (default: all enabled). Categories: task_created, task_deleted, task_status, task_assignments, task_updates, task_subtasks, task_comments, project_created, project_deleted, project_updates, project_contacts, portal_updates, portal_settings, time_entries, entity_files, lead_created, lead_deleted, lead_status, lead_updates, lead_interactions, lead_proposals, lead_contacts, lead_conversions, contact_created, contact_deleted, contact_updates, team_members, api_keys, agent_suggestions, agent_activity, agent_goals, agent_autonomous' },
      { name: 'email_notifications_enabled', type: 'boolean', required: false, description: 'Master toggle for email notifications. Must be true for any email notifications to send. Default: false.' },
      { name: 'email_notification_prefs', type: 'object', required: false, description: 'Email notification preferences. JSON object mapping category keys to booleans (default: all disabled). Same categories as notification_prefs. Set a category to true to receive email notifications for it.' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/team-members/:id', description: 'Permanently delete a team member. Cascades to API keys, assignments, and notifications.', group: 'Team Members',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Team member ID' }],
  },

  // ─── Activities (Audit) ───────────────────────────────────────────
  { method: 'GET', path: '/api/v1/activities', description: 'System-generated audit trail of all entity changes — who changed what and when. Read-only. Not for logging agent events (use /agent-activities) or tracking human hours (use /time-entries).', group: 'Activities',
    queryParams: [
      { name: 'entity_type', type: 'string', description: 'Filter by entity type (task, project, lead, contact, etc.)' },
      { name: 'entity_id', type: 'uuid', description: 'Filter by entity ID' },
      { name: 'type', type: 'string', description: 'Filter by activity type (created, updated, deleted, etc.)' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },

  // ─── Projects ─────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/projects', description: 'List all projects with optional filtering. Returns each project with its member_ids array. Non-archived by default.', group: 'Projects',
    queryParams: [
      { name: 'status', type: 'active|completed|archived', description: 'Filter by project status' },
      { name: 'include_archived', type: 'boolean', description: 'Include soft-deleted projects (default false)' },
      { name: 'search', type: 'string', description: 'Search by name or description' },
      { name: 'autonomous_enabled', type: 'boolean', description: 'Filter by autonomous agents enabled/disabled' },
      { name: 'sort', type: 'string', description: 'Sort field (default created_at)' },
      { name: 'order', type: 'asc|desc', description: 'Sort order (default desc)' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects', description: 'Create a project. Optionally link an existing contact or create a new one inline as the primary client.', group: 'Projects',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Project name' },
      { name: 'description', type: 'string', required: false, description: 'Project description' },
      { name: 'color', type: 'string', required: false, description: 'Hex color (#RRGGBB) or empty string for no color' },
      { name: 'status', type: 'active|completed|archived', required: false, description: 'Project status (default active)' },
      { name: 'start_date', type: 'string|null', required: false, description: 'Start date (ISO date string or null)' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Due date (ISO date string or null)' },
      { name: 'hourly_tracking', type: 'boolean', required: false, description: 'Enable hourly time tracking (default false). Must be true to use /time-entries.' },
      { name: 'autonomous_enabled', type: 'boolean', required: false, description: 'Enable autonomous agent features (default false)' },
      { name: 'deployment_policy', type: 'playground|production', required: false, description: 'Deployment policy when autonomous is enabled (default production)' },
      { name: 'max_concurrent_tasks', type: 'number', required: false, description: 'Max tasks an agent may work on simultaneously (default 2). Requires agents enabled.' },
      { name: 'suggestions_per_cycle', type: 'number', required: false, description: 'Max suggestions an agent may propose per cycle (default 3). Requires agents enabled.' },
      { name: 'repo_path', type: 'string|null', required: false, description: 'Absolute path to the project codebase on the VPS (e.g. /home/user/Projects/my-project). Null for non-code projects.' },
      { name: 'member_ids', type: 'uuid[]', required: false, description: 'Team member IDs to assign to the project' },
      { name: 'contact_id', type: 'uuid|null', required: false, description: 'Existing contact ID to link as primary client. Takes priority over contact.' },
      { name: 'contact', type: 'object', required: false, description: 'Create a new contact inline: { name (required), email, phone, company }. Ignored if contact_id is set.' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id', description: 'Get a single project by ID. Returns the project with its member_ids array.', group: 'Projects',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id', description: 'Update a project. Only include fields you want to change. Pass member_ids to replace the full member list.', group: 'Projects',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'name', type: 'string', required: false, description: 'Project name' },
      { name: 'description', type: 'string', required: false, description: 'Project description' },
      { name: 'color', type: 'string', required: false, description: 'Hex color (#RRGGBB) or empty string for no color' },
      { name: 'status', type: 'active|completed|archived', required: false, description: 'Project status' },
      { name: 'start_date', type: 'string|null', required: false, description: 'Start date (ISO date string or null)' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Due date (ISO date string or null)' },
      { name: 'hourly_tracking', type: 'boolean', required: false, description: 'Enable/disable hourly time tracking' },
      { name: 'autonomous_enabled', type: 'boolean', required: false, description: 'Enable/disable autonomous agents' },
      { name: 'deployment_policy', type: 'playground|production', required: false, description: 'Deployment policy: playground or production' },
      { name: 'max_concurrent_tasks', type: 'number', required: false, description: 'Max tasks an agent may work on simultaneously' },
      { name: 'suggestions_per_cycle', type: 'number', required: false, description: 'Max suggestions an agent may propose per cycle' },
      { name: 'repo_path', type: 'string|null', required: false, description: 'Absolute path to the project codebase on the VPS. Set null to clear.' },
      { name: 'member_ids', type: 'uuid[]', required: false, description: 'Replace the full team member list (deletes existing, inserts these)' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id', description: 'Soft-delete (archive) a project by setting archived_at. Returns { archived: true, archived_at }.', group: 'Projects',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
  },

  // ─── Project Contacts ─────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/projects/:id/contacts', description: 'List contacts linked to a project, with their full contact record nested. Paginated.', group: 'Project Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/contacts', description: 'Link an existing contact to a project with a role. Use is_primary_client to mark the main client.', group: 'Project Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'contact_id', type: 'uuid', required: true, description: 'Contact ID to link' },
      { name: 'role', type: 'string', required: true, description: 'Role label (e.g. Client, Vendor, Partner)' },
      { name: 'custom_role', type: 'string|null', required: false, description: 'Custom role text (when role is "Other" or needs more specificity)' },
      { name: 'is_primary_client', type: 'boolean', required: false, description: 'Set as the primary client for this project (default false)' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/contacts/:contactId', description: 'Get a single project contact link with nested contact data', group: 'Project Contacts',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'contactId', type: 'uuid', required: true, description: 'Contact ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/contacts/:contactId', description: 'Update a project contact link (role, primary status)', group: 'Project Contacts',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'contactId', type: 'uuid', required: true, description: 'Contact ID' },
    ],
    body: [
      { name: 'role', type: 'string', required: false, description: 'Role label' },
      { name: 'custom_role', type: 'string|null', required: false, description: 'Custom role text' },
      { name: 'is_primary_client', type: 'boolean', required: false, description: 'Set as primary client' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/contacts/:contactId', description: 'Remove a contact from a project (does not delete the contact itself)', group: 'Project Contacts',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'contactId', type: 'uuid', required: true, description: 'Contact ID' },
    ],
  },

  // ─── Portal ───────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/projects/:id/portal', description: 'Get client portal settings for a project. Returns the portal config including token, PIN, and visibility toggles.', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
  },
  { method: 'PUT', path: '/api/v1/projects/:id/portal', description: 'Create or update client portal settings. This is an upsert — creates settings if they don\'t exist, or updates if they do.', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'enabled', type: 'boolean', required: false, description: 'Enable/disable the portal' },
      { name: 'pin', type: 'string|null', required: false, description: 'PIN for portal access (null to remove)' },
      { name: 'welcome_message', type: 'string', required: false, description: 'Welcome message shown on portal' },
      { name: 'logo_url', type: 'string', required: false, description: 'Logo image URL' },
      { name: 'accent_color', type: 'string', required: false, description: 'Hex color (e.g. #5B8A8A)' },
      { name: 'show_progress', type: 'boolean', required: false, description: 'Show progress section' },
      { name: 'show_files', type: 'boolean', required: false, description: 'Show files section' },
      { name: 'show_hours', type: 'boolean', required: false, description: 'Show hours section' },
      { name: 'show_updates', type: 'boolean', required: false, description: 'Show updates timeline section' },
      { name: 'show_credentials', type: 'boolean', required: false, description: 'Show credentials submission section (allows clients to submit logins/keys)' },
      { name: 'show_invoices', type: 'boolean', required: false, description: 'Show invoices section' },
      { name: 'section_order', type: 'string[]', required: false, description: 'Ordered array of section keys controlling display order on the portal' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/portal/updates', description: 'List portal updates (client-visible project timeline entries). Each update includes an attachments array with any linked files. Paginated, newest first.', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/portal/updates', description: 'Create a portal update — a timeline entry visible to the client on the portal.', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'title', type: 'string', required: true, description: 'Update title' },
      { name: 'content', type: 'string', required: false, description: 'Update body text' },
      { name: 'update_type', type: 'general|milestone|deliverable|note', required: false, description: 'Update type (default general)' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/portal/updates/:updateId', description: 'Edit a portal update', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'updateId', type: 'uuid', required: true, description: 'Portal update ID' },
    ],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Update title' },
      { name: 'content', type: 'string', required: false, description: 'Update body text' },
      { name: 'update_type', type: 'general|milestone|deliverable|note', required: false, description: 'Update type' },
      { name: 'pinned', type: 'boolean', required: false, description: 'Pin the update (reserved for future use)' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/portal/updates/:updateId', description: 'Delete a portal update', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'updateId', type: 'uuid', required: true, description: 'Portal update ID' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/portal/updates/:updateId/attachments', description: 'List file attachments on a portal update. Returns files linked to the specified update, sorted by creation time ascending. Paginated.', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'updateId', type: 'uuid', required: true, description: 'Portal update ID' },
    ],
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/portal/updates/:updateId/attachments', description: 'Attach a file to a portal update. Provide the file URL (already uploaded to storage). The attachment will be visible to clients viewing the update on the portal.', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'updateId', type: 'uuid', required: true, description: 'Portal update ID' },
    ],
    body: [
      { name: 'name', type: 'string', required: true, description: 'File display name (e.g. "logo-concept-A.png")' },
      { name: 'file_url', type: 'string', required: true, description: 'URL to the uploaded file' },
      { name: 'file_size', type: 'number', required: false, description: 'File size in bytes (default 0)' },
      { name: 'mime_type', type: 'string', required: false, description: 'MIME type (default application/octet-stream). Used for display — images render as thumbnails on the portal.' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/portal/updates/:updateId/attachments/:attachmentId', description: 'Remove a file attachment from a portal update. Does not delete the file from storage.', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'updateId', type: 'uuid', required: true, description: 'Portal update ID' },
      { name: 'attachmentId', type: 'uuid', required: true, description: 'Attachment ID' },
    ],
  },

  // ─── Credentials ───────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/projects/:id/credentials', description: 'List credentials stored for a project. Returns metadata only — encrypted fields (username, password, URL, notes) are never included. Use the /reveal endpoint to decrypt. Paginated.', group: 'Credentials',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/credentials', description: 'Store an encrypted credential for a project. Field values are encrypted server-side with AES-256-GCM before storage. Each category has its own expected field keys (login: username/password/url; api_key: api_key/api_secret/url; ssh_key: host/username/private_key/passphrase; database: host/port/database/username/password; credit_card: cardholder/card_number/expiry/cvc/billing_zip; ach: account_holder/bank_name/routing_number/account_number/account_type). Requires PROJECT_CREDENTIALS_ENCRYPTION_KEY to be configured.', group: 'Credentials',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'label', type: 'string', required: true, description: 'Display name (e.g. "WordPress Admin", "Stripe API Key")' },
      { name: 'category', type: 'login|api_key|ssh_key|database|credit_card|ach', required: false, description: 'Credential category (default login)' },
      { name: 'fields', type: 'object', required: false, description: 'Category-specific field values as a string-to-string map, e.g. {"username": "...", "password": "..."} (encrypted at rest)' },
      { name: 'username', type: 'string', required: false, description: 'Legacy shorthand for fields.username (encrypted at rest)' },
      { name: 'password', type: 'string', required: false, description: 'Legacy shorthand for fields.password (encrypted at rest)' },
      { name: 'url', type: 'string', required: false, description: 'Legacy shorthand for fields.url (encrypted at rest)' },
      { name: 'notes', type: 'string', required: false, description: 'Additional notes (encrypted at rest)' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/credentials/:credentialId', description: 'Get credential metadata by ID. Returns label, category, timestamps, and submission info — but NOT the encrypted secret fields. Use /reveal to decrypt.', group: 'Credentials',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'credentialId', type: 'uuid', required: true, description: 'Credential ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/credentials/:credentialId', description: 'Update a credential. Metadata fields (label, category) are updated directly. Secret fields (username, password, url, notes) trigger a decrypt-merge-reencrypt cycle — only include fields you want to change.', group: 'Credentials',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'credentialId', type: 'uuid', required: true, description: 'Credential ID' },
    ],
    body: [
      { name: 'label', type: 'string', required: false, description: 'Display name' },
      { name: 'category', type: 'login|api_key|ssh_key|database|credit_card|ach', required: false, description: 'Credential category' },
      { name: 'fields', type: 'object', required: false, description: 'Field values to change as a string-to-string map; omitted keys are preserved (re-encrypts the credential)' },
      { name: 'username', type: 'string', required: false, description: 'Legacy shorthand for fields.username (re-encrypts the credential)' },
      { name: 'password', type: 'string', required: false, description: 'Legacy shorthand for fields.password (re-encrypts the credential)' },
      { name: 'url', type: 'string', required: false, description: 'Legacy shorthand for fields.url (re-encrypts the credential)' },
      { name: 'notes', type: 'string', required: false, description: 'New notes (re-encrypts the credential)' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/credentials/:credentialId', description: 'Permanently delete a credential and its encrypted data. This cannot be undone.', group: 'Credentials',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'credentialId', type: 'uuid', required: true, description: 'Credential ID' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/credentials/:credentialId/reveal', description: 'Decrypt and return the full credential payload as a string-to-string map of category-specific fields. This action is audit-logged separately as a "credential_reveal" event for security tracking. Requires encryption to be configured.', group: 'Credentials',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'credentialId', type: 'uuid', required: true, description: 'Credential ID' },
    ],
  },

  // ─── Time Entries ─────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/projects/:id/time-entries', description: 'List human work hour entries for a project. Use this for billing queries. Filter by member or running status. Paginated.', group: 'Time Entries',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID (must have hourly_tracking enabled)' }],
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
      { name: 'member_id', type: 'uuid', description: 'Filter by team member' },
      { name: 'running', type: 'boolean', description: 'Filter by running timers (true = only running, false = only completed)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/time-entries', description: 'Track human work hours for billing. Two modes: (1) Manual entry — provide member_id + start_time + end_time. (2) Live timer — provide only member_id (optionally description) to start a timer at the current time. This is for HUMAN time tracking, not agent activity. Bare timestamps without Z or offset are interpreted in the given timezone, or the API key owner\'s timezone preference, or UTC.', group: 'Time Entries',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID (must have hourly_tracking enabled)' }],
    body: [
      { name: 'member_id', type: 'uuid', required: true, description: 'Team member ID' },
      { name: 'start_time', type: 'string', required: false, description: 'ISO datetime. Required for manual entries. Omit entirely to start a live timer.' },
      { name: 'end_time', type: 'string', required: false, description: 'ISO datetime. Required for manual entries. Omit entirely to start a live timer.' },
      { name: 'description', type: 'string', required: false, description: 'What was worked on' },
      { name: 'timezone', type: 'string', required: false, description: 'IANA timezone (e.g. America/Phoenix). Only applies to manual entries. Bare timestamps are interpreted in this timezone. Falls back to the API key owner\'s timezone preference if omitted.' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/time-entries/:entryId', description: 'Get a single time entry by ID', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/time-entries/:entryId', description: 'Update a time entry. Set end_time to null to re-open a completed timer. For finalized entries, updating start_time or end_time without supplying segments collapses the entry to a single [start, end] segment; pass segments explicitly to preserve multi-segment pause history. For unfinalized entries (running or paused), updating start_time or end_time without an explicit segments array returns a 400 — send segments yourself so state-machine transitions stay deliberate.', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID' },
    ],
    body: [
      { name: 'member_id', type: 'uuid', required: false, description: 'Reassign to a different team member' },
      { name: 'start_time', type: 'string', required: false, description: 'ISO datetime' },
      { name: 'end_time', type: 'string|null', required: false, description: 'ISO datetime, or null to re-open as a running timer' },
      { name: 'segments', type: 'array', required: false, description: 'Worked intervals: [{start: ISO, end: ISO | null}]. Advanced: direct segment rewrites bypass pause/resume invariants, so ensure end_time stays consistent with the last segment.' },
      { name: 'description', type: 'string', required: false, description: 'What was worked on' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/time-entries/:entryId', description: 'Permanently delete a time entry', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/time-entries/:entryId/stop', description: 'Finalize a timer. Closes any open segment at now and sets end_time. Works from both running and paused states. Fails if the timer is already finalized.', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID (must be unfinalized — end_time is null)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/time-entries/:entryId/pause', description: 'Pause a running timer. Closes the current open segment with an end timestamp at now, leaving end_time null so the timer stays unfinalized. Fails if the timer is already paused or finalized. Paused timers whose last segment ended on a previous calendar day are auto-finalized on next resume attempt.', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID (must be a running timer — end_time null and last segment open)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/time-entries/:entryId/resume', description: 'Resume a paused timer by appending a new open segment starting at now. Fails if the timer is running or finalized. If the last segment ended on a previous calendar day (in the member\'s timezone), auto-finalizes the entry instead of resuming.', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID (must be a paused timer — end_time null and last segment closed)' },
    ],
  },

  // ─── Tasks ────────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/tasks', description: 'List all tasks across projects with filtering. Each task includes inline subtasks, comments, and assignee_ids. Paginated.', group: 'Tasks',
    queryParams: [
      { name: 'status', type: 'todo|in_progress|in_review|done', description: 'Filter by task status' },
      { name: 'priority', type: 'low|medium|high|urgent', description: 'Filter by priority' },
      { name: 'project_id', type: 'uuid', description: 'Filter by project' },
      { name: 'assignee_id', type: 'uuid', description: 'Filter by assigned team member' },
      { name: 'task_type', type: 'string', description: 'Filter by type: engineering, research, audit, marketing, copywriting, operations, general' },
      { name: 'ai_managed', type: 'boolean', description: 'Filter by AI managed flag (true = AI managed, false = manual)' },
      { name: 'project_goal_id', type: 'uuid', description: 'Filter by linked project goal' },
      { name: 'search', type: 'string', description: 'Search by task title or description' },
      { name: 'sort', type: 'string', description: 'Sort field (default created_at)' },
      { name: 'order', type: 'asc|desc', description: 'Sort order (default desc)' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/tasks', description: 'Create a task within a project. Optionally assign team members, set a due date, link to a goal, and tag it.', group: 'Tasks',
    body: [
      { name: 'project_id', type: 'uuid', required: true, description: 'Project ID this task belongs to' },
      { name: 'title', type: 'string', required: true, description: 'Task title' },
      { name: 'description', type: 'string', required: false, description: 'Task description (supports plain text)' },
      { name: 'status', type: 'todo|in_progress|in_review|done', required: false, description: 'Initial status (default todo)' },
      { name: 'priority', type: 'low|medium|high|urgent', required: false, description: 'Priority level (default medium)' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Due date (ISO date string or null)' },
      { name: 'tags', type: 'string[]', required: false, description: 'Tag labels' },
      { name: 'assignee_ids', type: 'uuid[]', required: false, description: 'Team member IDs to assign' },
      { name: 'task_type', type: 'string|null', required: false, description: 'Task type: engineering, research, audit, marketing, copywriting, operations, general (or null)' },
      { name: 'ai_managed', type: 'boolean', required: false, description: 'Whether AI agents manage this task (default true)' },
      { name: 'project_goal_id', type: 'uuid|null', required: false, description: 'Link this task to a project goal' },
    ],
  },
  { method: 'GET', path: '/api/v1/tasks/:id', description: 'Get a single task with its subtasks (sorted by sort_order), comments (sorted by created_at), and assignee_ids', group: 'Tasks',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Task ID' }],
  },
  { method: 'PATCH', path: '/api/v1/tasks/:id', description: 'Update a task. Only include fields you want to change. Pass assignee_ids to replace the full assignee list.', group: 'Tasks',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Task ID' }],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Task title' },
      { name: 'description', type: 'string', required: false, description: 'Task description' },
      { name: 'status', type: 'todo|in_progress|in_review|done', required: false, description: 'Task status' },
      { name: 'priority', type: 'low|medium|high|urgent', required: false, description: 'Priority level' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Due date or null to clear' },
      { name: 'tags', type: 'string[]', required: false, description: 'Replace tag labels' },
      { name: 'assignee_ids', type: 'uuid[]', required: false, description: 'Replace the full assignee list (deletes existing, inserts these)' },
      { name: 'project_id', type: 'uuid', required: false, description: 'Move task to a different project' },
      { name: 'task_type', type: 'string|null', required: false, description: 'Task type or null' },
      { name: 'ai_managed', type: 'boolean', required: false, description: 'Set AI managed flag (true = AI managed, false = manual)' },
      { name: 'project_goal_id', type: 'uuid|null', required: false, description: 'Link to a goal or null to unlink' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/tasks/:id', description: 'Permanently delete a task and its subtasks, comments, and assignees', group: 'Tasks',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Task ID' }],
  },
  { method: 'POST', path: '/api/v1/tasks/reorder', description: 'Move a task to a new position within its column (same project + status). Shifts sibling sort_order values to maintain a contiguous sequence.', group: 'Tasks',
    body: [
      { name: 'task_id', type: 'uuid', required: true, description: 'The task to move' },
      { name: 'new_sort_order', type: 'number', required: true, description: 'Target position index (0-based). Clamped to the valid range.' },
    ],
  },

  // ─── Subtasks ─────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/tasks/:id/subtasks', description: 'List subtasks for a task, ordered by sort_order', group: 'Subtasks',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Parent task ID' }],
  },
  { method: 'POST', path: '/api/v1/tasks/:id/subtasks', description: 'Add a subtask (checklist item) to a task. Appended to the end of the sort order.', group: 'Subtasks',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Parent task ID' }],
    body: [{ name: 'title', type: 'string', required: true, description: 'Subtask title' }],
  },
  { method: 'PUT', path: '/api/v1/tasks/:id/subtasks/reorder', description: 'Set the display order of subtasks. Provide all subtask IDs in the desired order.', group: 'Subtasks',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Parent task ID' }],
    body: [{ name: 'subtask_ids', type: 'uuid[]', required: true, description: 'All subtask IDs in the desired display order' }],
  },
  { method: 'PATCH', path: '/api/v1/tasks/:id/subtasks/:subtaskId', description: 'Update a subtask — toggle completion or rename it', group: 'Subtasks',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Parent task ID' },
      { name: 'subtaskId', type: 'uuid', required: true, description: 'Subtask ID' },
    ],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Subtask title' },
      { name: 'completed', type: 'boolean', required: false, description: 'Whether the subtask is done' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/tasks/:id/subtasks/:subtaskId', description: 'Delete a subtask', group: 'Subtasks',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Parent task ID' },
      { name: 'subtaskId', type: 'uuid', required: true, description: 'Subtask ID' },
    ],
  },

  // ─── Comments ─────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/tasks/:id/comments', description: 'List comments on a task, ordered by created_at ascending', group: 'Comments',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Task ID' }],
  },
  { method: 'POST', path: '/api/v1/tasks/:id/comments', description: 'Add a comment to a task. Specify the author via user_id (team member ID).', group: 'Comments',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Task ID' }],
    body: [
      { name: 'user_id', type: 'uuid', required: true, description: 'Author team member ID' },
      { name: 'text', type: 'string', required: true, description: 'Comment text' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/tasks/:id/comments/:commentId', description: 'Edit a comment\'s text', group: 'Comments',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Task ID' },
      { name: 'commentId', type: 'uuid', required: true, description: 'Comment ID' },
    ],
    body: [
      { name: 'text', type: 'string', required: true, description: 'Updated comment text (min 1 character)' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/tasks/:id/comments/:commentId', description: 'Delete a comment', group: 'Comments',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Task ID' },
      { name: 'commentId', type: 'uuid', required: true, description: 'Comment ID' },
    ],
  },

  // ─── Leads ────────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/leads', description: 'List all leads (sales pipeline). Non-archived by default. Each lead includes its member_ids array. Paginated with search and sort.', group: 'Leads',
    queryParams: [
      { name: 'status', type: 'new|contacted|qualified|proposal|won|lost', description: 'Filter by pipeline status' },
      { name: 'source', type: 'referral|website|social|cold_outreach|event|network|other', description: 'Filter by lead source' },
      { name: 'assigned_to', type: 'uuid', description: 'Filter by assigned team member' },
      { name: 'include_archived', type: 'boolean', description: 'Include soft-deleted leads (default false)' },
      { name: 'search', type: 'string', description: 'Search by name, email, or company' },
      { name: 'sort', type: 'string', description: 'Sort field (default created_at)' },
      { name: 'order', type: 'asc|desc', description: 'Sort order (default desc)' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/leads', description: 'Create a lead in the sales pipeline. If no contact_id is provided, a contact is automatically created and linked from the lead data (name, email, phone, company).', group: 'Leads',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Lead / prospect name' },
      { name: 'email', type: 'string', required: false, description: 'Email address (defaults to empty string)' },
      { name: 'phone', type: 'string', required: false, description: 'Phone number (defaults to empty string)' },
      { name: 'company', type: 'string', required: false, description: 'Company name (defaults to empty string)' },
      { name: 'source', type: 'referral|website|social|cold_outreach|event|network|other', required: false, description: 'How the lead was acquired (default other)' },
      { name: 'status', type: 'new|contacted|qualified|proposal|won|lost', required: false, description: 'Pipeline status (default new)' },
      { name: 'value', type: 'number|null', required: false, description: 'Deal value in dollars' },
      { name: 'equity', type: 'number|null', required: false, description: 'Equity percentage (0-100)' },
      { name: 'notes', type: 'string', required: false, description: 'Free-text notes (defaults to empty string)' },
      { name: 'assigned_to', type: 'uuid|null', required: false, description: 'Primary assigned team member ID' },
      { name: 'contact_id', type: 'uuid|null', required: false, description: 'Link an existing contact. If omitted, a new contact is auto-created from the lead data.' },
      { name: 'member_ids', type: 'uuid[]', required: false, description: 'Team member IDs involved with this lead' },
    ],
  },
  { method: 'GET', path: '/api/v1/leads/:id', description: 'Get a single lead by ID with its member_ids array', group: 'Leads',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
  },
  { method: 'PATCH', path: '/api/v1/leads/:id', description: 'Update a lead. Only include fields you want to change. Pass member_ids to replace the full member list.', group: 'Leads',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    body: [
      { name: 'name', type: 'string', required: false, description: 'Lead name' },
      { name: 'email', type: 'string', required: false, description: 'Email address' },
      { name: 'phone', type: 'string', required: false, description: 'Phone number' },
      { name: 'company', type: 'string', required: false, description: 'Company name' },
      { name: 'source', type: 'referral|website|social|cold_outreach|event|network|other', required: false, description: 'Lead source' },
      { name: 'status', type: 'new|contacted|qualified|proposal|won|lost', required: false, description: 'Pipeline status' },
      { name: 'value', type: 'number|null', required: false, description: 'Deal value' },
      { name: 'equity', type: 'number|null', required: false, description: 'Equity percentage' },
      { name: 'notes', type: 'string', required: false, description: 'Notes' },
      { name: 'assigned_to', type: 'uuid|null', required: false, description: 'Primary assigned team member' },
      { name: 'contact_id', type: 'uuid|null', required: false, description: 'Linked contact ID' },
      { name: 'member_ids', type: 'uuid[]', required: false, description: 'Replace the full team member list' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/leads/:id', description: 'Soft-delete (archive) a lead by setting archived_at. Returns { archived: true, archived_at }.', group: 'Leads',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
  },
  { method: 'POST', path: '/api/v1/leads/:id/convert', description: 'Convert a lead into a project. Creates a project, links the contact as primary client, copies team members, and sets the lead status to "won".', group: 'Leads',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    body: [
      { name: 'project_name', type: 'string', required: true, description: 'Name for the new project' },
      { name: 'project_color', type: 'string', required: false, description: 'Hex color (#RRGGBB) for the new project' },
      { name: 'project_description', type: 'string', required: false, description: 'Description for the new project' },
    ],
  },

  // ─── Lead Contacts ────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/leads/:id/contacts', description: 'List contacts linked to a lead, with nested contact data', group: 'Lead Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
  },
  { method: 'POST', path: '/api/v1/leads/:id/contacts', description: 'Link an existing contact to a lead with a role', group: 'Lead Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    body: [
      { name: 'contact_id', type: 'uuid', required: true, description: 'Contact ID to link' },
      { name: 'role', type: 'string', required: true, description: 'Role label (e.g. Decision Maker, Technical Contact)' },
      { name: 'custom_role', type: 'string|null', required: false, description: 'Custom role text' },
      { name: 'is_primary_client', type: 'boolean', required: false, description: 'Set as primary client (default false)' },
    ],
  },
  { method: 'GET', path: '/api/v1/leads/:id/contacts/:contactId', description: 'Get a single lead contact link', group: 'Lead Contacts',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'contactId', type: 'uuid', required: true, description: 'Contact ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/leads/:id/contacts/:contactId', description: 'Update a lead contact link (role, primary status)', group: 'Lead Contacts',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'contactId', type: 'uuid', required: true, description: 'Contact ID' },
    ],
    body: [
      { name: 'role', type: 'string', required: false, description: 'Role label' },
      { name: 'custom_role', type: 'string|null', required: false, description: 'Custom role text' },
      { name: 'is_primary_client', type: 'boolean', required: false, description: 'Set as primary client' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/leads/:id/contacts/:contactId', description: 'Remove a contact from a lead (does not delete the contact itself)', group: 'Lead Contacts',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'contactId', type: 'uuid', required: true, description: 'Contact ID' },
    ],
  },

  // ─── Lead Interactions ────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/leads/:id/interactions', description: 'List interactions (calls, emails, meetings, notes) for a lead. Paginated.', group: 'Lead Interactions',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    queryParams: [
      { name: 'type', type: 'call|email|meeting|note|follow_up', description: 'Filter by interaction type' },
      { name: 'completed', type: 'boolean', description: 'Filter by completion status' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/leads/:id/interactions', description: 'Log an interaction with a lead — a call, email, meeting, note, or follow-up', group: 'Lead Interactions',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    body: [
      { name: 'title', type: 'string', required: true, description: 'Interaction title / subject' },
      { name: 'type', type: 'call|email|meeting|note|follow_up', required: false, description: 'Interaction type (default note)' },
      { name: 'description', type: 'string', required: false, description: 'Details or summary (defaults to empty string)' },
      { name: 'occurred_at', type: 'string', required: false, description: 'When the interaction occurred (ISO datetime, defaults to now)' },
      { name: 'scheduled_at', type: 'string|null', required: false, description: 'Scheduled datetime for follow-ups (null if not scheduled)' },
      { name: 'completed', type: 'boolean', required: false, description: 'Whether the interaction is completed (default false)' },
    ],
  },
  { method: 'GET', path: '/api/v1/leads/:id/interactions/:interactionId', description: 'Get a single interaction', group: 'Lead Interactions',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'interactionId', type: 'uuid', required: true, description: 'Interaction ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/leads/:id/interactions/:interactionId', description: 'Update an interaction. Only include fields you want to change.', group: 'Lead Interactions',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'interactionId', type: 'uuid', required: true, description: 'Interaction ID' },
    ],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Interaction title' },
      { name: 'type', type: 'call|email|meeting|note|follow_up', required: false, description: 'Interaction type' },
      { name: 'description', type: 'string', required: false, description: 'Details or summary' },
      { name: 'occurred_at', type: 'string', required: false, description: 'When the interaction occurred (ISO datetime)' },
      { name: 'scheduled_at', type: 'string|null', required: false, description: 'Scheduled datetime (or null)' },
      { name: 'completed', type: 'boolean', required: false, description: 'Completion status' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/leads/:id/interactions/:interactionId', description: 'Delete an interaction', group: 'Lead Interactions',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'interactionId', type: 'uuid', required: true, description: 'Interaction ID' },
    ],
  },

  // ─── Lead Proposals ───────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/leads/:id/proposals', description: 'List proposals sent to a lead. Filter by status. Paginated.', group: 'Lead Proposals',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    queryParams: [
      { name: 'status', type: 'draft|sent|accepted|rejected', description: 'Filter by proposal status' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/leads/:id/proposals', description: 'Create a proposal for a lead', group: 'Lead Proposals',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    body: [
      { name: 'title', type: 'string', required: true, description: 'Proposal title' },
      { name: 'description', type: 'string', required: false, description: 'Proposal body / scope (defaults to empty string)' },
      { name: 'estimated_value', type: 'number|null', required: false, description: 'Estimated deal value in dollars' },
      { name: 'status', type: 'draft|sent|accepted|rejected', required: false, description: 'Proposal status (default draft)' },
      { name: 'sent_at', type: 'string|null', required: false, description: 'When the proposal was sent to the client (ISO datetime or null)' },
    ],
  },
  { method: 'GET', path: '/api/v1/leads/:id/proposals/:proposalId', description: 'Get a single proposal', group: 'Lead Proposals',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'proposalId', type: 'uuid', required: true, description: 'Proposal ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/leads/:id/proposals/:proposalId', description: 'Update a proposal. Only include fields you want to change.', group: 'Lead Proposals',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'proposalId', type: 'uuid', required: true, description: 'Proposal ID' },
    ],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Proposal title' },
      { name: 'description', type: 'string', required: false, description: 'Proposal body / scope' },
      { name: 'estimated_value', type: 'number|null', required: false, description: 'Estimated deal value' },
      { name: 'status', type: 'draft|sent|accepted|rejected', required: false, description: 'Proposal status' },
      { name: 'sent_at', type: 'string|null', required: false, description: 'When sent (ISO datetime or null)' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/leads/:id/proposals/:proposalId', description: 'Delete a proposal', group: 'Lead Proposals',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'proposalId', type: 'uuid', required: true, description: 'Proposal ID' },
    ],
  },

  // ─── Lead Fields ──────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/leads/:id/fields', description: 'List custom key-value fields attached to a lead', group: 'Lead Fields',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
  },
  { method: 'PUT', path: '/api/v1/leads/:id/fields', description: 'Upsert custom fields on a lead. Creates new fields or updates existing ones by field_key.', group: 'Lead Fields',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Lead ID' }],
    body: [{ name: 'fields', type: '{ field_key: string, value: string }[]', required: true, description: 'Array of key-value pairs. field_key must be non-empty. value must be a string.' }],
  },
  { method: 'GET', path: '/api/v1/leads/:id/fields/:fieldId', description: 'Get a single custom field by ID', group: 'Lead Fields',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'fieldId', type: 'uuid', required: true, description: 'Lead field ID' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/leads/:id/fields/:fieldId', description: 'Delete a custom field', group: 'Lead Fields',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Lead ID' },
      { name: 'fieldId', type: 'uuid', required: true, description: 'Lead field ID' },
    ],
  },

  // ─── Goals (requires NEXT_PUBLIC_ENABLE_AGENTS=true) ──────────────
  { method: 'GET', path: '/api/v1/projects/:id/goals', description: 'List goals for a project. Goals are high-level objectives that tasks and suggestions can be linked to. Paginated.', group: 'Goals',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    queryParams: [
      { name: 'status', type: 'active|achieved|paused|abandoned', description: 'Filter by goal status' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/goals', description: 'Create a goal for a project. Goals group related tasks and suggestions under a strategic objective. Requires agents to be enabled.', group: 'Goals',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'title', type: 'string', required: true, description: 'Goal title' },
      { name: 'description', type: 'string', required: false, description: 'Goal description / success criteria' },
      { name: 'target_date', type: 'string|null', required: false, description: 'Target completion date (YYYY-MM-DD or null)' },
      { name: 'status', type: 'active|achieved|paused|abandoned', required: false, description: 'Goal status (default active)' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/goals/:goalId', description: 'Get a goal with rollup stats: pending/approved/total suggestions and total/completed/in-progress task counts', group: 'Goals',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'goalId', type: 'uuid', required: true, description: 'Goal ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/goals/:goalId', description: 'Update a goal. Only include fields you want to change. Requires agents to be enabled.', group: 'Goals',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'goalId', type: 'uuid', required: true, description: 'Goal ID' },
    ],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Goal title' },
      { name: 'description', type: 'string', required: false, description: 'Goal description' },
      { name: 'target_date', type: 'string|null', required: false, description: 'Target date or null to clear' },
      { name: 'status', type: 'active|achieved|paused|abandoned', required: false, description: 'Goal status' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/goals/:goalId', description: 'Archive a goal (soft delete). Requires agents to be enabled.', group: 'Goals',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'goalId', type: 'uuid', required: true, description: 'Goal ID' },
    ],
  },

  // ─── Project Context (requires NEXT_PUBLIC_ENABLE_AGENTS=true) ─────
  { method: 'GET', path: '/api/v1/projects/:id/context', description: 'List project knowledge entries. Returns structured context that agents use to understand the project: business context, existing work, technical decisions, constraints, and lessons learned.', group: 'Project Context',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    queryParams: [
      { name: 'category', type: 'business_context|existing_work|technical_decision|constraint|lesson_learned', description: 'Filter by category' },
      { name: 'is_active', type: 'boolean', description: 'Filter by active status (default true). Set to false to include deactivated entries.' },
      { name: 'since', type: 'string', description: 'Only return entries updated on or after this ISO datetime' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/context', description: 'Add a knowledge entry to a project. For category "existing_work" with a file_path, this upserts: if an active entry with the same file_path exists, it updates instead of creating a duplicate.', group: 'Project Context',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'category', type: 'business_context|existing_work|technical_decision|constraint|lesson_learned', required: true, description: 'Knowledge category' },
      { name: 'content', type: 'string', required: true, description: 'Main content of the entry' },
      { name: 'source', type: 'human|agent|scan', required: false, description: 'Who created this entry (default human)' },
      { name: 'file_path', type: 'string|null', required: false, description: 'File path for existing_work entries. Enables upsert behavior.' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/context/:entryId', description: 'Update a project context entry. Only include fields you want to change.', group: 'Project Context',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Context entry ID' },
    ],
    body: [
      { name: 'content', type: 'string', required: false, description: 'Entry content' },
      { name: 'source', type: 'human|agent|scan', required: false, description: 'Entry source' },
      { name: 'category', type: 'business_context|existing_work|technical_decision|constraint|lesson_learned', required: false, description: 'Change the category' },
      { name: 'is_active', type: 'boolean', required: false, description: 'Set to false to deactivate' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/context/:entryId', description: 'Soft-delete a project context entry by setting is_active to false. The entry is preserved but excluded from default queries.', group: 'Project Context',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Context entry ID' },
    ],
  },

  // ─── Task Suggestions (requires NEXT_PUBLIC_ENABLE_AGENTS=true) ───
  { method: 'GET', path: '/api/v1/task-suggestions', description: 'List task suggestions proposed by agents. Suggestions go through a review workflow: pending -> approved (creates a task) or rejected. Paginated.', group: 'Task Suggestions',
    queryParams: [
      { name: 'status', type: 'pending|needs_info|approved|rejected', description: 'Filter by review status' },
      { name: 'project_id', type: 'uuid', description: 'Filter by project' },
      { name: 'goal_id', type: 'uuid', description: 'Filter by goal' },
      { name: 'proposed_by', type: 'uuid', description: 'Filter by the agent member ID that proposed it' },
      { name: 'task_type', type: 'string', description: 'Filter by type: engineering, research, audit, marketing, copywriting, operations, general' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/task-suggestions', description: 'Propose a new task for human review. Agent-only — the API key must be linked to a team member with role "agent". Creates a pending suggestion that admins can approve, reject, or request more info on.', group: 'Task Suggestions',
    body: [
      { name: 'project_id', type: 'uuid', required: true, description: 'Project this suggestion is for' },
      { name: 'goal_id', type: 'uuid', required: true, description: 'Goal this suggestion supports' },
      { name: 'title', type: 'string', required: true, description: 'Suggested task title' },
      { name: 'description', type: 'string', required: true, description: 'Detailed description of what the task would involve' },
      { name: 'reasoning', type: 'string', required: true, description: 'Why this task is needed — justification for the reviewer' },
      { name: 'priority', type: 'low|medium|high|urgent', required: false, description: 'Suggested priority (default medium)' },
      { name: 'effort_estimate', type: 'small|medium|large|null', required: false, description: 'Estimated effort level (default null)' },
      { name: 'assigned_to', type: 'uuid|null', required: false, description: 'Suggested assignee team member ID (default null)' },
      { name: 'task_type', type: 'string|null', required: false, description: 'Task type: engineering, research, audit, marketing, copywriting, operations, general (or null)' },
      { name: 'metadata', type: 'object', required: false, description: 'Arbitrary JSON metadata (default {})' },
    ],
  },
  { method: 'GET', path: '/api/v1/task-suggestions/:id', description: 'Get a single suggestion with full details', group: 'Task Suggestions',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Suggestion ID' }],
  },
  { method: 'PATCH', path: '/api/v1/task-suggestions/:id', description: 'Edit a suggestion before approval. Update content fields or metadata. Use /approve, /reject, or /request-info for status changes.', group: 'Task Suggestions',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Suggestion ID' }],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Suggestion title' },
      { name: 'description', type: 'string', required: false, description: 'Suggestion description' },
      { name: 'reasoning', type: 'string', required: false, description: 'Justification for the suggestion' },
      { name: 'priority', type: 'low|medium|high|urgent', required: false, description: 'Suggested priority' },
      { name: 'effort_estimate', type: 'small|medium|large|null', required: false, description: 'Estimated effort level' },
      { name: 'task_type', type: 'string|null', required: false, description: 'Task type: engineering, research, audit, marketing, copywriting, operations, general (or null)' },
      { name: 'metadata', type: 'object', required: false, description: 'Merge these keys into the existing metadata object' },
    ],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/:id/approve', description: 'Approve a suggestion and create a real task from it. Only works on suggestions with status "pending" or "needs_info". Optionally override fields on the created task.', group: 'Task Suggestions',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Suggestion ID' }],
    body: [
      { name: 'priority', type: 'low|medium|high|urgent', required: false, description: 'Override the suggested priority' },
      { name: 'assigned_to', type: 'uuid|null', required: false, description: 'Override the suggested assignee' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Set a due date on the created task' },
      { name: 'project_id', type: 'uuid', required: false, description: 'Override the project (move to a different project)' },
      { name: 'task_type', type: 'string', required: false, description: 'Set the task type on the created task' },
      { name: 'ai_managed', type: 'boolean', required: false, description: 'Set to false to approve as a manual (human-managed) task. Defaults to true (AI-managed).' },
    ],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/:id/reject', description: 'Reject a suggestion. Cannot reject an already-approved or already-rejected suggestion. When a rejection_reason is provided, a "lesson_learned" entry is automatically added to the project context so agents can learn from the feedback.', group: 'Task Suggestions',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Suggestion ID' }],
    body: [{ name: 'rejection_reason', type: 'string', required: false, description: 'Reason for rejection (visible to the proposing agent). Also saved as a lesson_learned in project context.' }],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/:id/request-info', description: 'Ask the proposing agent for more information. Sets status to "needs_info". Only works on suggestions with status "pending".', group: 'Task Suggestions',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Suggestion ID' }],
    body: [{ name: 'info_request', type: 'string', required: true, description: 'What additional information is needed' }],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/bulk-approve', description: 'Approve multiple suggestions at once. Skips suggestions that are not in "pending" or "needs_info" status. Returns per-item results.', group: 'Task Suggestions',
    body: [{ name: 'ids', type: 'uuid[]', required: true, description: 'Array of suggestion IDs to approve' }],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/bulk-reject', description: 'Reject multiple suggestions at once. Skips suggestions that are already approved or rejected. Returns per-item results.', group: 'Task Suggestions',
    body: [
      { name: 'ids', type: 'uuid[]', required: true, description: 'Array of suggestion IDs to reject' },
      { name: 'rejection_reason', type: 'string', required: false, description: 'Shared rejection reason applied to all' },
    ],
  },

  // ─── Agent Activity (requires NEXT_PUBLIC_ENABLE_AGENTS=true) ─────
  { method: 'GET', path: '/api/v1/agent-activities', description: 'Query agent orchestration events — task lifecycle, research progress, sub-agent spawning, and operational telemetry. This is for automated agent actions, NOT human time tracking (use /time-entries) or audit logs (use /activities). Paginated.', group: 'Agent Activity',
    queryParams: [
      { name: 'agent_id', type: 'uuid', description: 'Filter by agent team member ID' },
      { name: 'project_id', type: 'uuid', description: 'Filter by project' },
      { name: 'activity_type', type: 'string', description: 'Filter by type: suggestion_created, task_started, task_completed, task_failed, research_started, research_completed, suggestion_reviewed, comment_added, status_changed, agent_spawned, agent_completed, agent_failed, heartbeat, system_check, custom' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/agent-activities', description: 'Log an agent orchestration event. Use this to record what an agent did — task lifecycle, research, sub-agent spawning, heartbeats, system checks. Agent-only: the API key must be linked to a team member with role "agent".', group: 'Agent Activity',
    body: [
      { name: 'activity_type', type: 'string', required: true, description: 'Event type: suggestion_created, task_started, task_completed, task_failed, research_started, research_completed, suggestion_reviewed, comment_added, status_changed, agent_spawned, agent_completed, agent_failed, heartbeat, system_check, custom' },
      { name: 'title', type: 'string', required: true, description: 'Short summary of what happened' },
      { name: 'description', type: 'string', required: false, description: 'Detailed description (defaults to empty string)' },
      { name: 'project_id', type: 'uuid|null', required: false, description: 'Related project (default null)' },
      { name: 'reference_type', type: 'string|null', required: false, description: 'Referenced entity type (e.g. task, suggestion, goal)' },
      { name: 'reference_id', type: 'uuid|null', required: false, description: 'Referenced entity ID' },
      { name: 'metadata', type: 'object', required: false, description: 'Arbitrary JSON metadata (default {})' },
    ],
  },

  // ─── Audit Log ────────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/audit-log', description: 'List API audit log entries. Every API write operation is logged here with before/after snapshots. Use this to review what changed and when. Paginated.', group: 'Audit Log',
    queryParams: [
      { name: 'entity_type', type: 'string', description: 'Filter by entity type (task, project, lead, contact, etc.)' },
      { name: 'entity_id', type: 'uuid', description: 'Filter by entity ID' },
      { name: 'team_member_id', type: 'uuid', description: 'Filter by team member who made the change' },
      { name: 'method', type: 'POST|PATCH|PUT|DELETE', description: 'Filter by HTTP method' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'GET', path: '/api/v1/audit-log/:entityType/:entityId', description: 'Get the full change history for a specific entity. Returns all audit log entries for that entity, newest first.', group: 'Audit Log',
    params: [
      { name: 'entityType', type: 'string', required: true, description: 'Entity type (task, project, lead, contact, etc.)' },
      { name: 'entityId', type: 'uuid', required: true, description: 'Entity ID' },
    ],
  },

  // ─── Entity Files ─────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/entity-files', description: 'List file attachments for an entity (lead, project, or contact). Both entity_type and entity_id are required as query params. Paginated.', group: 'Entity Files',
    queryParams: [
      { name: 'entity_type', type: 'lead|project|contact', description: 'Entity type (required)' },
      { name: 'entity_id', type: 'uuid', description: 'Entity ID (required)' },
      { name: 'visibility', type: 'internal|external', description: 'Filter by visibility. If omitted, returns all files.' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/entity-files', description: 'Attach a file to a lead, project, or contact. Provide the file URL (already uploaded to storage).', group: 'Entity Files',
    body: [
      { name: 'entity_type', type: 'lead|project|contact', required: true, description: 'What type of entity to attach the file to' },
      { name: 'entity_id', type: 'uuid', required: true, description: 'Entity ID' },
      { name: 'name', type: 'string', required: true, description: 'File display name' },
      { name: 'file_url', type: 'string', required: true, description: 'URL to the uploaded file' },
      { name: 'file_size', type: 'number', required: false, description: 'File size in bytes (default 0)' },
      { name: 'mime_type', type: 'string', required: false, description: 'MIME type (default application/octet-stream)' },
      { name: 'visibility', type: 'internal|external', required: false, description: 'File visibility (default internal). Files with external visibility are shown on the client portal.' },
      { name: 'uploaded_by', type: 'uuid|null', required: false, description: 'Team member ID of uploader' },
    ],
  },
  { method: 'GET', path: '/api/v1/entity-files/:fileId', description: 'Get a single file attachment by ID', group: 'Entity Files',
    params: [{ name: 'fileId', type: 'uuid', required: true, description: 'Entity file ID' }],
  },
  { method: 'PATCH', path: '/api/v1/entity-files/:fileId', description: 'Update a file attachment (name or visibility)', group: 'Entity Files',
    params: [{ name: 'fileId', type: 'uuid', required: true, description: 'Entity file ID' }],
    body: [
      { name: 'name', type: 'string', required: false, description: 'New file name' },
      { name: 'visibility', type: 'internal|external', required: false, description: 'File visibility. External files are shown on the client portal.' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/entity-files/:fileId', description: 'Delete a file attachment', group: 'Entity Files',
    params: [{ name: 'fileId', type: 'uuid', required: true, description: 'Entity file ID' }],
  },

  // ─── Notifications ────────────────────────────────────────────────
  { method: 'GET', path: '/api/v1/notifications', description: 'List notifications for the team member linked to this API key. Requires the API key to be linked to a team member. Paginated.', group: 'Notifications',
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
      { name: 'is_read', type: 'boolean', description: 'Filter by read status (true = read only, false = unread only)' },
      { name: 'entity_type', type: 'string', description: 'Filter by entity type: task, project, lead, comment, member, contact, suggestion, goal' },
    ],
  },
  { method: 'GET', path: '/api/v1/notifications/:id', description: 'Get a single notification by ID. Must belong to the API key\'s linked team member.', group: 'Notifications',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Notification ID' }],
  },
  { method: 'PATCH', path: '/api/v1/notifications/:id', description: 'Mark a notification as read or unread', group: 'Notifications',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Notification ID' }],
    body: [
      { name: 'is_read', type: 'boolean', required: true, description: 'Set to true to mark read, false to mark unread' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/notifications/:id', description: 'Delete a notification', group: 'Notifications',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Notification ID' }],
  },
  { method: 'POST', path: '/api/v1/notifications/mark-all-read', description: 'Mark all unread notifications as read for the API key\'s linked team member. No request body needed.', group: 'Notifications' },
];

export const groups = [...new Set(endpoints.map(e => e.group))];

export const METHOD_COLORS: Record<string, string> = {
  GET: 'bg-emerald-100 text-emerald-700',
  POST: 'bg-blue-100 text-blue-700',
  PUT: 'bg-amber-100 text-amber-700',
  PATCH: 'bg-orange-100 text-orange-700',
  DELETE: 'bg-red-100 text-red-700',
};
