export interface EndpointDoc {
  method: string;
  path: string;
  description: string;
  group: string;
  params?: { name: string; type: string; required: boolean; description: string }[];
  queryParams?: { name: string; type: string; description: string }[];
  body?: { name: string; type: string; required: boolean; description: string }[];
}

export const endpoints: EndpointDoc[] = [
  // Contacts
  { method: 'GET', path: '/api/v1/contacts', description: 'List all contacts', group: 'Contacts',
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
      { name: 'search', type: 'string', description: 'Search by name, email, or company' },
      { name: 'sort', type: 'string', description: 'Sort field (default created_at)' },
      { name: 'order', type: 'asc|desc', description: 'Sort order (default desc)' },
    ],
  },
  { method: 'POST', path: '/api/v1/contacts', description: 'Create a contact', group: 'Contacts',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Contact name' },
      { name: 'email', type: 'string', required: false, description: 'Email address' },
      { name: 'phone', type: 'string', required: false, description: 'Phone number' },
      { name: 'company', type: 'string', required: false, description: 'Company name' },
      { name: 'notes', type: 'string', required: false, description: 'Notes' },
      { name: 'color', type: 'string', required: false, description: 'Hex color (default brand color)' },
      { name: 'avatar_url', type: 'string', required: false, description: 'Avatar image URL' },
    ],
  },
  { method: 'GET', path: '/api/v1/contacts/:id', description: 'Get a contact by ID', group: 'Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Contact ID' }],
  },
  { method: 'PATCH', path: '/api/v1/contacts/:id', description: 'Update a contact', group: 'Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Contact ID' }],
  },
  { method: 'DELETE', path: '/api/v1/contacts/:id', description: 'Delete a contact', group: 'Contacts',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Contact ID' }],
  },

  // Team Members
  { method: 'GET', path: '/api/v1/team-members', description: 'List all team members', group: 'Team Members',
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number' },
      { name: 'limit', type: 'number', description: 'Items per page' },
      { name: 'search', type: 'string', description: 'Search by name or email' },
    ],
  },
  { method: 'POST', path: '/api/v1/team-members', description: 'Create a team member', group: 'Team Members',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Member name' },
      { name: 'email', type: 'string', required: true, description: 'Email address' },
      { name: 'role', type: 'admin|member|guest|agent', required: false, description: 'Role (default member)' },
      { name: 'timezone', type: 'string', required: false, description: 'IANA timezone (default UTC)' },
    ],
  },
  { method: 'GET', path: '/api/v1/team-members/:id', description: 'Get a team member', group: 'Team Members' },
  { method: 'PATCH', path: '/api/v1/team-members/:id', description: 'Update a team member', group: 'Team Members',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Team member ID' }],
    body: [
      { name: 'name', type: 'string', required: false, description: 'Display name' },
      { name: 'email', type: 'string', required: false, description: 'Email address' },
      { name: 'avatar', type: 'string', required: false, description: 'Avatar URL' },
      { name: 'role', type: 'admin|member|guest|agent', required: false, description: 'Role' },
      { name: 'timezone', type: 'string', required: false, description: 'IANA timezone (e.g. America/New_York). Used for displaying times and as default timezone for API time entries.' },
      { name: 'notification_prefs', type: 'object', required: false, description: 'Notification preferences. JSON object mapping category keys to booleans. Categories: task_created, task_deleted, task_status, task_assignments, task_updates, task_subtasks, task_comments, project_created, project_deleted, project_updates, project_contacts, portal_updates, portal_settings, portal_files, time_entries, entity_files, lead_created, lead_deleted, lead_status, lead_updates, lead_interactions, lead_proposals, lead_contacts, lead_conversions, contact_created, contact_deleted, contact_updates, team_members, api_keys, agent_suggestions, agent_activity, agent_goals, agent_autonomous' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/team-members/:id', description: 'Delete a team member', group: 'Team Members' },

  // Activities
  { method: 'GET', path: '/api/v1/activities', description: 'List activities (audit log)', group: 'Activities',
    queryParams: [
      { name: 'entity_type', type: 'string', description: 'Filter by entity type (task, project, etc.)' },
      { name: 'entity_id', type: 'string', description: 'Filter by entity ID' },
      { name: 'type', type: 'string', description: 'Filter by activity type' },
    ],
  },

  // Projects
  { method: 'GET', path: '/api/v1/projects', description: 'List all projects', group: 'Projects',
    queryParams: [
      { name: 'status', type: 'string', description: 'Filter by status (active, completed, archived)' },
      { name: 'include_archived', type: 'boolean', description: 'Include soft-deleted projects' },
      { name: 'search', type: 'string', description: 'Search by name or description' },
      { name: 'autonomous_enabled', type: 'boolean', description: 'Filter by autonomous agents enabled/disabled' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects', description: 'Create a project. Optionally link an existing contact or create a new one inline as the primary client.', group: 'Projects',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Project name' },
      { name: 'description', type: 'string', required: false, description: 'Description' },
      { name: 'color', type: 'string', required: false, description: 'Hex color' },
      { name: 'status', type: 'string', required: false, description: 'Status (default active)' },
      { name: 'start_date', type: 'string|null', required: false, description: 'Start date' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Due date' },
      { name: 'hourly_tracking', type: 'boolean', required: false, description: 'Enable hourly time tracking (default false)' },
      { name: 'autonomous_enabled', type: 'boolean', required: false, description: 'Enable autonomous agents (default false)' },
      { name: 'member_ids', type: 'uuid[]', required: false, description: 'Team member IDs' },
      { name: 'contact_id', type: 'uuid|null', required: false, description: 'Existing contact ID to link as primary client' },
      { name: 'contact', type: 'object', required: false, description: 'Create a new contact inline: { name (required), email, phone, company }. Ignored if contact_id is set.' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id', description: 'Get a project', group: 'Projects' },
  { method: 'PATCH', path: '/api/v1/projects/:id', description: 'Update a project', group: 'Projects',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'name', type: 'string', required: false, description: 'Project name' },
      { name: 'description', type: 'string', required: false, description: 'Description' },
      { name: 'color', type: 'string', required: false, description: 'Hex color' },
      { name: 'status', type: 'string', required: false, description: 'Status (active, completed, archived)' },
      { name: 'start_date', type: 'string|null', required: false, description: 'Start date' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Due date' },
      { name: 'hourly_tracking', type: 'boolean', required: false, description: 'Enable/disable hourly time tracking' },
      { name: 'autonomous_enabled', type: 'boolean', required: false, description: 'Enable/disable autonomous agents' },
      { name: 'member_ids', type: 'uuid[]', required: false, description: 'Replace team member IDs' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id', description: 'Soft-delete (archive) a project', group: 'Projects' },

  // Project Contacts
  { method: 'GET', path: '/api/v1/projects/:id/contacts', description: 'List project contacts', group: 'Project Contacts' },
  { method: 'POST', path: '/api/v1/projects/:id/contacts', description: 'Add contact to project', group: 'Project Contacts',
    body: [
      { name: 'contact_id', type: 'uuid', required: true, description: 'Contact ID' },
      { name: 'role', type: 'string', required: true, description: 'Role' },
      { name: 'is_primary_client', type: 'boolean', required: false, description: 'Set as primary client' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/contacts/:contactId', description: 'Get a project contact', group: 'Project Contacts' },
  { method: 'PATCH', path: '/api/v1/projects/:id/contacts/:contactId', description: 'Update project contact role', group: 'Project Contacts' },
  { method: 'DELETE', path: '/api/v1/projects/:id/contacts/:contactId', description: 'Remove contact from project', group: 'Project Contacts' },

  // Portal
  { method: 'GET', path: '/api/v1/projects/:id/portal', description: 'Get portal settings', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
  },
  { method: 'PUT', path: '/api/v1/projects/:id/portal', description: 'Update portal settings', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'enabled', type: 'boolean', required: false, description: 'Enable/disable the portal' },
      { name: 'pin', type: 'string|null', required: false, description: 'PIN for portal access (null to remove)' },
      { name: 'welcome_message', type: 'string', required: false, description: 'Welcome message shown on portal' },
      { name: 'logo_url', type: 'string', required: false, description: 'Logo image URL' },
      { name: 'accent_color', type: 'string', required: false, description: 'Hex color (e.g. #5B8A8A)' },
      { name: 'show_progress', type: 'boolean', required: false, description: 'Show progress section' },
      { name: 'show_proposals', type: 'boolean', required: false, description: 'Show proposals section' },
      { name: 'show_files', type: 'boolean', required: false, description: 'Show files section' },
      { name: 'show_hours', type: 'boolean', required: false, description: 'Show hours section' },
      { name: 'show_updates', type: 'boolean', required: false, description: 'Show updates timeline section' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/portal/regenerate-token', description: 'Regenerate portal token. Returns updated settings with new token.', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
  },
  { method: 'GET', path: '/api/v1/projects/:id/portal/files', description: 'List portal files', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
  },
  { method: 'POST', path: '/api/v1/projects/:id/portal/files', description: 'Add a portal file', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'name', type: 'string', required: true, description: 'File name' },
      { name: 'file_url', type: 'string', required: true, description: 'File URL' },
      { name: 'file_size', type: 'number', required: true, description: 'File size in bytes' },
      { name: 'mime_type', type: 'string', required: true, description: 'MIME type (e.g. application/pdf)' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/portal/files/:fileId', description: 'Rename a portal file', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'fileId', type: 'uuid', required: true, description: 'Portal file ID' },
    ],
    body: [
      { name: 'name', type: 'string', required: true, description: 'New file name' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/portal/files/:fileId', description: 'Delete a portal file', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'fileId', type: 'uuid', required: true, description: 'Portal file ID' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/portal/updates', description: 'List portal updates', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/portal/updates', description: 'Create a portal update', group: 'Portal',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    body: [
      { name: 'title', type: 'string', required: true, description: 'Update title' },
      { name: 'content', type: 'string', required: false, description: 'Update content text' },
      { name: 'update_type', type: 'string', required: false, description: "Type: 'general' (default), 'milestone', 'deliverable', 'note'" },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/portal/updates/:updateId', description: 'Edit a portal update', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'updateId', type: 'uuid', required: true, description: 'Portal update ID' },
    ],
    body: [
      { name: 'title', type: 'string', required: false, description: 'Update title' },
      { name: 'content', type: 'string', required: false, description: 'Update content text' },
      { name: 'update_type', type: 'string', required: false, description: "Type: 'general', 'milestone', 'deliverable', 'note'" },
      { name: 'pinned', type: 'boolean', required: false, description: 'Pin the update (reserved for future use)' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/portal/updates/:updateId', description: 'Delete a portal update', group: 'Portal',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'updateId', type: 'uuid', required: true, description: 'Portal update ID' },
    ],
  },

  // Time Entries
  { method: 'GET', path: '/api/v1/projects/:id/time-entries', description: 'List time entries for a project', group: 'Time Entries',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID' }],
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
      { name: 'member_id', type: 'uuid', description: 'Filter by team member' },
      { name: 'running', type: 'boolean', description: 'Filter by running timers (true = only running, false = only completed)' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/time-entries', description: 'Create a manual time entry or start a live timer. Bare timestamps (without Z or offset) are interpreted in the given timezone, or the API key owner\'s timezone preference, or UTC.', group: 'Time Entries',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Project ID (must have hourly_tracking enabled)' }],
    body: [
      { name: 'member_id', type: 'uuid', required: true, description: 'Team member ID' },
      { name: 'start_time', type: 'string', required: false, description: 'ISO datetime (omit to start a live timer with current time)' },
      { name: 'end_time', type: 'string', required: false, description: 'ISO datetime (omit to start a live timer)' },
      { name: 'description', type: 'string', required: false, description: 'Entry description' },
      { name: 'timezone', type: 'string', required: false, description: 'IANA timezone (e.g. America/Phoenix). Bare timestamps are interpreted in this timezone. Falls back to the API key owner\'s timezone preference if omitted.' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/time-entries/:entryId', description: 'Get a single time entry', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/projects/:id/time-entries/:entryId', description: 'Update a time entry', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID' },
    ],
    body: [
      { name: 'member_id', type: 'uuid', required: false, description: 'Team member ID' },
      { name: 'start_time', type: 'string', required: false, description: 'ISO datetime' },
      { name: 'end_time', type: 'string|null', required: false, description: 'ISO datetime or null to re-open timer' },
      { name: 'description', type: 'string', required: false, description: 'Entry description' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/projects/:id/time-entries/:entryId', description: 'Delete a time entry', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/time-entries/:entryId/stop', description: 'Stop a running timer (sets end_time to now)', group: 'Time Entries',
    params: [
      { name: 'id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'entryId', type: 'uuid', required: true, description: 'Time entry ID (must be a running timer)' },
    ],
  },

  // Tasks
  { method: 'GET', path: '/api/v1/tasks', description: 'List all tasks', group: 'Tasks',
    queryParams: [
      { name: 'status', type: 'string', description: 'Filter by status (todo, in_progress, in_review, done)' },
      { name: 'priority', type: 'string', description: 'Filter by priority (low, medium, high, urgent)' },
      { name: 'project_id', type: 'uuid', description: 'Filter by project' },
      { name: 'assignee_id', type: 'uuid', description: 'Filter by assignee' },
      { name: 'task_type', type: 'string', description: 'Filter by task type (engineering, research, audit, marketing, copywriting, operations, general)' },
      { name: 'project_goal_id', type: 'uuid', description: 'Filter by project goal' },
    ],
  },
  { method: 'POST', path: '/api/v1/tasks', description: 'Create a task', group: 'Tasks',
    body: [
      { name: 'project_id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'title', type: 'string', required: true, description: 'Task title' },
      { name: 'description', type: 'string', required: false, description: 'Task description' },
      { name: 'status', type: 'string', required: false, description: 'Status: todo, in_progress, in_review, done (default todo)' },
      { name: 'priority', type: 'string', required: false, description: 'Priority: low, medium, high, urgent (default medium)' },
      { name: 'due_date', type: 'string|null', required: false, description: 'Due date' },
      { name: 'tags', type: 'string[]', required: false, description: 'Tags array' },
      { name: 'assignee_ids', type: 'uuid[]', required: false, description: 'Assignee member IDs' },
      { name: 'task_type', type: 'string', required: false, description: 'Task type: engineering, research, audit, marketing, copywriting, operations, general' },
      { name: 'project_goal_id', type: 'uuid', required: false, description: 'Link task to a project goal' },
    ],
  },
  { method: 'GET', path: '/api/v1/tasks/:id', description: 'Get a task with subtasks and comments', group: 'Tasks' },
  { method: 'PATCH', path: '/api/v1/tasks/:id', description: 'Update a task', group: 'Tasks' },
  { method: 'DELETE', path: '/api/v1/tasks/:id', description: 'Delete a task', group: 'Tasks' },

  // Subtasks
  { method: 'GET', path: '/api/v1/tasks/:id/subtasks', description: 'List subtasks', group: 'Subtasks' },
  { method: 'POST', path: '/api/v1/tasks/:id/subtasks', description: 'Create a subtask', group: 'Subtasks',
    body: [{ name: 'title', type: 'string', required: true, description: 'Subtask title' }],
  },
  { method: 'PUT', path: '/api/v1/tasks/:id/subtasks/reorder', description: 'Reorder subtasks', group: 'Subtasks',
    body: [{ name: 'subtask_ids', type: 'uuid[]', required: true, description: 'Ordered array of subtask IDs' }],
  },
  { method: 'PATCH', path: '/api/v1/tasks/:id/subtasks/:subtaskId', description: 'Update a subtask', group: 'Subtasks' },
  { method: 'DELETE', path: '/api/v1/tasks/:id/subtasks/:subtaskId', description: 'Delete a subtask', group: 'Subtasks' },

  // Comments
  { method: 'GET', path: '/api/v1/tasks/:id/comments', description: 'List comments on a task', group: 'Comments' },
  { method: 'POST', path: '/api/v1/tasks/:id/comments', description: 'Add a comment', group: 'Comments',
    body: [
      { name: 'user_id', type: 'uuid', required: true, description: 'Author team member ID' },
      { name: 'text', type: 'string', required: true, description: 'Comment text' },
    ],
  },
  { method: 'PATCH', path: '/api/v1/tasks/:id/comments/:commentId', description: 'Update a comment', group: 'Comments' },
  { method: 'DELETE', path: '/api/v1/tasks/:id/comments/:commentId', description: 'Delete a comment', group: 'Comments' },

  // Leads
  { method: 'GET', path: '/api/v1/leads', description: 'List all leads', group: 'Leads',
    queryParams: [
      { name: 'status', type: 'string', description: 'Filter by status' },
      { name: 'source', type: 'string', description: 'Filter by source' },
      { name: 'assigned_to', type: 'uuid', description: 'Filter by assigned member' },
      { name: 'include_archived', type: 'boolean', description: 'Include soft-deleted leads' },
    ],
  },
  { method: 'POST', path: '/api/v1/leads', description: 'Create a lead. A contact is automatically created and linked if no contact_id is provided.', group: 'Leads',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Lead name' },
      { name: 'email', type: 'string', required: false, description: 'Email' },
      { name: 'phone', type: 'string', required: false, description: 'Phone number' },
      { name: 'company', type: 'string', required: false, description: 'Company' },
      { name: 'source', type: 'string', required: false, description: 'Source: referral, website, social, cold_outreach, event, network, other (default other)' },
      { name: 'status', type: 'string', required: false, description: 'Status: new, contacted, qualified, proposal, won, lost (default new)' },
      { name: 'value', type: 'number|null', required: false, description: 'Deal value' },
      { name: 'equity', type: 'number|null', required: false, description: 'Equity percentage' },
      { name: 'notes', type: 'string', required: false, description: 'Notes' },
      { name: 'assigned_to', type: 'uuid|null', required: false, description: 'Assigned team member ID' },
      { name: 'contact_id', type: 'uuid|null', required: false, description: 'Existing contact ID. If omitted, a new contact is auto-created from the lead data.' },
      { name: 'member_ids', type: 'uuid[]', required: false, description: 'Team member IDs' },
    ],
  },
  { method: 'GET', path: '/api/v1/leads/:id', description: 'Get a lead', group: 'Leads' },
  { method: 'PATCH', path: '/api/v1/leads/:id', description: 'Update a lead', group: 'Leads' },
  { method: 'DELETE', path: '/api/v1/leads/:id', description: 'Soft-delete (archive) a lead', group: 'Leads' },
  { method: 'POST', path: '/api/v1/leads/:id/convert', description: 'Convert lead to project', group: 'Leads',
    body: [
      { name: 'project_name', type: 'string', required: true, description: 'New project name' },
      { name: 'project_color', type: 'string', required: false, description: 'Hex color' },
      { name: 'project_description', type: 'string', required: false, description: 'Project description' },
    ],
  },

  // Lead Contacts
  { method: 'GET', path: '/api/v1/leads/:id/contacts', description: 'List lead contacts', group: 'Lead Contacts' },
  { method: 'POST', path: '/api/v1/leads/:id/contacts', description: 'Add contact to lead', group: 'Lead Contacts' },
  { method: 'GET', path: '/api/v1/leads/:id/contacts/:contactId', description: 'Get a lead contact', group: 'Lead Contacts' },
  { method: 'PATCH', path: '/api/v1/leads/:id/contacts/:contactId', description: 'Update lead contact', group: 'Lead Contacts' },
  { method: 'DELETE', path: '/api/v1/leads/:id/contacts/:contactId', description: 'Remove contact from lead', group: 'Lead Contacts' },

  // Lead Interactions
  { method: 'GET', path: '/api/v1/leads/:id/interactions', description: 'List lead interactions', group: 'Lead Interactions',
    queryParams: [
      { name: 'type', type: 'string', description: 'Filter by type (call, email, meeting, note, follow_up)' },
      { name: 'completed', type: 'boolean', description: 'Filter by completion status' },
    ],
  },
  { method: 'POST', path: '/api/v1/leads/:id/interactions', description: 'Create an interaction', group: 'Lead Interactions' },
  { method: 'GET', path: '/api/v1/leads/:id/interactions/:interactionId', description: 'Get an interaction', group: 'Lead Interactions' },
  { method: 'PATCH', path: '/api/v1/leads/:id/interactions/:interactionId', description: 'Update an interaction', group: 'Lead Interactions' },
  { method: 'DELETE', path: '/api/v1/leads/:id/interactions/:interactionId', description: 'Delete an interaction', group: 'Lead Interactions' },

  // Lead Proposals
  { method: 'GET', path: '/api/v1/leads/:id/proposals', description: 'List lead proposals', group: 'Lead Proposals',
    queryParams: [{ name: 'status', type: 'string', description: 'Filter by status (draft, sent, accepted, rejected)' }],
  },
  { method: 'POST', path: '/api/v1/leads/:id/proposals', description: 'Create a proposal', group: 'Lead Proposals' },
  { method: 'GET', path: '/api/v1/leads/:id/proposals/:proposalId', description: 'Get a proposal', group: 'Lead Proposals' },
  { method: 'PATCH', path: '/api/v1/leads/:id/proposals/:proposalId', description: 'Update a proposal', group: 'Lead Proposals' },
  { method: 'DELETE', path: '/api/v1/leads/:id/proposals/:proposalId', description: 'Delete a proposal', group: 'Lead Proposals' },

  // Lead Fields
  { method: 'GET', path: '/api/v1/leads/:id/fields', description: 'List lead fields', group: 'Lead Fields' },
  { method: 'PUT', path: '/api/v1/leads/:id/fields', description: 'Upsert lead fields', group: 'Lead Fields',
    body: [{ name: 'fields', type: 'array', required: true, description: 'Array of { field_key, value }' }],
  },
  { method: 'GET', path: '/api/v1/leads/:id/fields/:fieldId', description: 'Get a lead field', group: 'Lead Fields' },
  { method: 'DELETE', path: '/api/v1/leads/:id/fields/:fieldId', description: 'Delete a lead field', group: 'Lead Fields' },

  // Project Goals (requires NEXT_PUBLIC_ENABLE_AGENTS=true)
  { method: 'GET', path: '/api/v1/projects/:id/goals', description: 'List goals for a project', group: 'Goals',
    queryParams: [
      { name: 'status', type: 'string', description: 'Filter by status (active, achieved, paused, abandoned)' },
      { name: 'page', type: 'number', description: 'Page number' },
      { name: 'limit', type: 'number', description: 'Items per page' },
    ],
  },
  { method: 'POST', path: '/api/v1/projects/:id/goals', description: 'Create a goal for a project', group: 'Goals',
    body: [
      { name: 'title', type: 'string', required: true, description: 'Goal title' },
      { name: 'description', type: 'string', required: false, description: 'Goal description' },
      { name: 'target_date', type: 'string', required: false, description: 'Target date (YYYY-MM-DD)' },
      { name: 'status', type: 'string', required: false, description: 'Status (default active)' },
    ],
  },
  { method: 'GET', path: '/api/v1/projects/:id/goals/:goalId', description: 'Get a goal with rollup stats', group: 'Goals' },
  { method: 'PATCH', path: '/api/v1/projects/:id/goals/:goalId', description: 'Update a goal', group: 'Goals' },
  { method: 'DELETE', path: '/api/v1/projects/:id/goals/:goalId', description: 'Archive a goal (soft delete)', group: 'Goals' },

  // Task Suggestions (requires NEXT_PUBLIC_ENABLE_AGENTS=true)
  { method: 'GET', path: '/api/v1/task-suggestions', description: 'List all task suggestions', group: 'Task Suggestions',
    queryParams: [
      { name: 'status', type: 'string', description: 'Filter by status (pending, needs_info, approved, rejected)' },
      { name: 'project_id', type: 'uuid', description: 'Filter by project' },
      { name: 'goal_id', type: 'uuid', description: 'Filter by goal' },
      { name: 'proposed_by', type: 'uuid', description: 'Filter by agent member ID' },
      { name: 'task_type', type: 'string', description: 'Filter by task type (engineering, research, audit, marketing, copywriting, operations, general)' },
      { name: 'page', type: 'number', description: 'Page number' },
      { name: 'limit', type: 'number', description: 'Items per page' },
    ],
  },
  { method: 'POST', path: '/api/v1/task-suggestions', description: 'Create a suggestion (agent only)', group: 'Task Suggestions',
    body: [
      { name: 'project_id', type: 'uuid', required: true, description: 'Project ID' },
      { name: 'goal_id', type: 'uuid', required: true, description: 'Goal ID' },
      { name: 'title', type: 'string', required: true, description: 'Suggestion title' },
      { name: 'description', type: 'string', required: true, description: 'Detailed description' },
      { name: 'reasoning', type: 'string', required: true, description: 'Why this task is needed' },
      { name: 'priority', type: 'string', required: false, description: 'Priority (default medium)' },
      { name: 'effort_estimate', type: 'string', required: false, description: 'Effort (small, medium, large)' },
      { name: 'assigned_to', type: 'uuid', required: false, description: 'Suggested assignee' },
      { name: 'task_type', type: 'string', required: false, description: 'Task type (engineering, research, audit, marketing, copywriting, operations, general)' },
      { name: 'metadata', type: 'object', required: false, description: 'Arbitrary metadata' },
    ],
  },
  { method: 'GET', path: '/api/v1/task-suggestions/:id', description: 'Get a suggestion', group: 'Task Suggestions' },
  { method: 'PATCH', path: '/api/v1/task-suggestions/:id', description: 'Update suggestion metadata', group: 'Task Suggestions' },
  { method: 'POST', path: '/api/v1/task-suggestions/:id/approve', description: 'Approve and create task', group: 'Task Suggestions',
    body: [
      { name: 'priority', type: 'string', required: false, description: 'Override priority' },
      { name: 'assigned_to', type: 'uuid', required: false, description: 'Override assignee' },
      { name: 'due_date', type: 'string', required: false, description: 'Set due date' },
      { name: 'project_id', type: 'uuid', required: false, description: 'Override project' },
      { name: 'task_type', type: 'string', required: false, description: 'Set task type for the created task' },
    ],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/:id/reject', description: 'Reject a suggestion', group: 'Task Suggestions',
    body: [{ name: 'rejection_reason', type: 'string', required: false, description: 'Reason for rejection' }],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/:id/request-info', description: 'Request more info on a suggestion', group: 'Task Suggestions',
    body: [{ name: 'info_request', type: 'string', required: true, description: 'What info is needed' }],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/bulk-approve', description: 'Bulk approve suggestions', group: 'Task Suggestions',
    body: [{ name: 'ids', type: 'uuid[]', required: true, description: 'Array of suggestion IDs' }],
  },
  { method: 'POST', path: '/api/v1/task-suggestions/bulk-reject', description: 'Bulk reject suggestions', group: 'Task Suggestions',
    body: [
      { name: 'ids', type: 'uuid[]', required: true, description: 'Array of suggestion IDs' },
      { name: 'rejection_reason', type: 'string', required: false, description: 'Shared reason for rejection' },
    ],
  },

  // Agent Activity (requires NEXT_PUBLIC_ENABLE_AGENTS=true)
  { method: 'GET', path: '/api/v1/agent-activities', description: 'List agent activity', group: 'Agent Activity',
    queryParams: [
      { name: 'agent_id', type: 'uuid', description: 'Filter by agent' },
      { name: 'project_id', type: 'uuid', description: 'Filter by project' },
      { name: 'activity_type', type: 'string', description: 'Filter by type (suggestion_created, task_started, task_completed, task_failed, research_completed, comment_added, status_changed, custom)' },
      { name: 'page', type: 'number', description: 'Page number' },
      { name: 'limit', type: 'number', description: 'Items per page' },
    ],
  },
  { method: 'POST', path: '/api/v1/agent-activities', description: 'Log agent activity (agent only)', group: 'Agent Activity',
    body: [
      { name: 'activity_type', type: 'string', required: true, description: 'Activity type (suggestion_created, task_started, task_completed, task_failed, research_completed, comment_added, status_changed, custom)' },
      { name: 'title', type: 'string', required: true, description: 'Activity title' },
      { name: 'description', type: 'string', required: false, description: 'Activity description' },
      { name: 'project_id', type: 'uuid', required: false, description: 'Related project' },
      { name: 'reference_type', type: 'string', required: false, description: 'Reference entity type' },
      { name: 'reference_id', type: 'uuid', required: false, description: 'Reference entity ID' },
      { name: 'metadata', type: 'object', required: false, description: 'Arbitrary metadata' },
    ],
  },

  // Audit Log
  { method: 'GET', path: '/api/v1/audit-log', description: 'List API audit log entries', group: 'Audit Log',
    queryParams: [
      { name: 'entity_type', type: 'string', description: 'Filter by entity type' },
      { name: 'entity_id', type: 'uuid', description: 'Filter by entity ID' },
      { name: 'team_member_id', type: 'uuid', description: 'Filter by team member' },
      { name: 'method', type: 'string', description: 'Filter by HTTP method' },
      { name: 'page', type: 'number', description: 'Page number' },
      { name: 'limit', type: 'number', description: 'Items per page' },
    ],
  },
  { method: 'GET', path: '/api/v1/audit-log/:entityType/:entityId', description: 'Get change history for an entity', group: 'Audit Log' },

  // Entity Files (file attachments for contacts, leads, projects)
  { method: 'GET', path: '/api/v1/entity-files', description: 'List file attachments for an entity', group: 'Entity Files',
    queryParams: [
      { name: 'entity_type', type: 'string', description: 'Entity type: lead, project, or contact (required)' },
      { name: 'entity_id', type: 'uuid', description: 'Entity ID (required)' },
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
    ],
  },
  { method: 'POST', path: '/api/v1/entity-files', description: 'Attach a file to an entity', group: 'Entity Files',
    body: [
      { name: 'entity_type', type: 'string', required: true, description: 'Entity type: lead, project, or contact' },
      { name: 'entity_id', type: 'uuid', required: true, description: 'Entity ID' },
      { name: 'name', type: 'string', required: true, description: 'File display name' },
      { name: 'file_url', type: 'string', required: true, description: 'URL to the file' },
      { name: 'file_size', type: 'number', required: false, description: 'File size in bytes (default 0)' },
      { name: 'mime_type', type: 'string', required: false, description: 'MIME type (default application/octet-stream)' },
      { name: 'uploaded_by', type: 'uuid|null', required: false, description: 'Team member ID of uploader' },
    ],
  },
  { method: 'GET', path: '/api/v1/entity-files/:fileId', description: 'Get a file attachment by ID', group: 'Entity Files',
    params: [{ name: 'fileId', type: 'uuid', required: true, description: 'Entity file ID' }],
  },
  { method: 'PATCH', path: '/api/v1/entity-files/:fileId', description: 'Rename a file attachment', group: 'Entity Files',
    params: [{ name: 'fileId', type: 'uuid', required: true, description: 'Entity file ID' }],
    body: [
      { name: 'name', type: 'string', required: true, description: 'New file name' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/entity-files/:fileId', description: 'Delete a file attachment', group: 'Entity Files',
    params: [{ name: 'fileId', type: 'uuid', required: true, description: 'Entity file ID' }],
  },

  // Notifications
  { method: 'GET', path: '/api/v1/notifications', description: 'List notifications for the team member linked to the API key', group: 'Notifications',
    queryParams: [
      { name: 'page', type: 'number', description: 'Page number (default 1)' },
      { name: 'limit', type: 'number', description: 'Items per page (default 25, max 100)' },
      { name: 'is_read', type: 'boolean', description: 'Filter by read status (true = read only, false = unread only)' },
      { name: 'entity_type', type: 'string', description: 'Filter by entity type (task, project, lead, comment, member, contact, suggestion, goal)' },
    ],
  },
  { method: 'GET', path: '/api/v1/notifications/:id', description: 'Get a notification by ID', group: 'Notifications',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Notification ID' }],
  },
  { method: 'PATCH', path: '/api/v1/notifications/:id', description: 'Update a notification (mark as read/unread)', group: 'Notifications',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Notification ID' }],
    body: [
      { name: 'is_read', type: 'boolean', required: true, description: 'Read status' },
    ],
  },
  { method: 'DELETE', path: '/api/v1/notifications/:id', description: 'Delete a notification', group: 'Notifications',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'Notification ID' }],
  },
  { method: 'POST', path: '/api/v1/notifications/mark-all-read', description: 'Mark all unread notifications as read for the team member linked to the API key', group: 'Notifications' },

  // API Keys
  { method: 'GET', path: '/api/v1/api-keys', description: 'List all API keys (includes revoked)', group: 'API Keys' },
  { method: 'POST', path: '/api/v1/api-keys', description: 'Create a new API key. The plain key is returned only once in the response.', group: 'API Keys',
    body: [
      { name: 'name', type: 'string', required: true, description: 'Display name for the key' },
      { name: 'permissions', type: 'full|read_only', required: false, description: 'Permission level (default full)' },
      { name: 'team_member_id', type: 'uuid|null', required: false, description: 'Link key to a team member (enables notification access and timezone defaults)' },
    ],
  },
  { method: 'GET', path: '/api/v1/api-keys/:id', description: 'Get an API key by ID', group: 'API Keys',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'API key ID' }],
  },
  { method: 'DELETE', path: '/api/v1/api-keys/:id', description: 'Revoke an API key (soft delete — sets revoked_at)', group: 'API Keys',
    params: [{ name: 'id', type: 'uuid', required: true, description: 'API key ID' }],
  },
];

export const groups = [...new Set(endpoints.map(e => e.group))];

export const METHOD_COLORS: Record<string, string> = {
  GET: 'bg-emerald-100 text-emerald-700',
  POST: 'bg-blue-100 text-blue-700',
  PUT: 'bg-amber-100 text-amber-700',
  PATCH: 'bg-orange-100 text-orange-700',
  DELETE: 'bg-red-100 text-red-700',
};
